import 'intl_keys.dart';

const en_US_res = {
  S.OK: 'OK',
  S.Cancel: 'Cancel',
  S.Next: 'Next',
  S.Connect: 'Connect',
  S.Dis: 'Disconnect',
  S.Disconnect: 'Disconnect',
  S.Devicenotconnected: 'Device not connected',
  S.Klotski: 'Klotski',
  S.NumberPuzzle: 'Number Puzzle',
  S.Classic: 'Classic',
  S.Practice: 'Practice',
  S.Stages: 'Stages',
  S.VS: '1 VS 1',
  S.Devices: 'Devices',
  S.Search: 'Search',
  S.Searching: 'Searching',
  S.Searchagain: 'Search again',
  S.Battery: 'Battery',
  S.Switch: 'Switch',
  S.FirmwareVersion: 'Firmware Version',
  S.Upgradefirmwareto: 'Upgrade firmware to ',
  S.Bluetoothnotenabled: 'Bluetooth not enabled',
  S.Enablebluetooth: 'Enable bluetooth',
  S.Renamedevice: 'Rename device',
  S.FirmwareUpgrade: 'Firmware Upgrade',
  S.FirmwareupgradingPleasedonotclosetheapp: 'Firmware upgrading,Please do not close the app',
  S.Customize: 'Customize',
  S.SlideTime: 'Slide & Time',
  S.AITutorial: 'AI Tutorial',
  S.StageSync: 'Stage Sync',
  S.syncappdevicestageprogress:
      'Your smart device stage progress is not the same as the app. Do you want to sync them?',
  S.Sync: 'Sync',
  S.Records: 'Records',
  S.Invite: 'Invite',
  S.Move: 'Moves',
  S.PreviousStep: 'Previous Step',
  S.Speed: ' x',
  S.Puttingoneselfinsomeoneelsesshoes: "Putting oneself in someone else's shoes",
  S.ThreeHeroesSwearBrotherhoodInThePeachGarden: 'Three Heroes Swear Brotherhood In The Peach Garden',
  S.FuXisEightTrigramsWaterKanTrigram: "Fu Xi's Eight Trigrams: Water Kan Trigram",
  S.PassFiveLevels: 'Pass Five Levels',
  S.Domineeringandtyrannical: 'Domineering and tyrannical',
  S.TheThreeBrothersFightAgainstLuBu: 'The Three Brothers Fight Against Lu Bu',
  S.Drawingaswordandmountingahorse: 'Drawing a sword and mounting a horse',
  S.LiuBeiPaysThreeVisitsToZhugeLiangscottage: 'Liu Bei Pays Three Visits To Zhuge Liang’s cottage',
  S.Settingfiretotheconnectedcamps: 'Setting fire to the connected camps',
  S.Devicenamemodifiedsuccessfully: 'Completed',
  S.Failed: 'Failed',
  S.FirmwareUpdateSuccessfully: 'Firmware update successfully',
  S.Back: 'Back',
  S.Newrecord: 'New record',
  S.Noscore: 'No score',
  S.PleaseselecttheStageyouwanttosync: 'Please select the Stage you want to sync',
  S.GANKlotski: 'GAN Klotski',
  S.Inprogress: 'In progress',
  S.SyncCompleted: 'Completed',
  S.automatching: 'Auto matching',
  S.Recommendedstage: 'Recommended stage',
  S.selectachessgame: 'select a chess game',
  S.quit: 'quit',
  S.Completed: 'Completed',
  S.pressOKafterplacingthepieces: "press 'OK' after placing the pieces",
  S.recordofClassic: 'record of Classic',
  S.Chessgame: 'Chess game',
  S.moves: 'moves',
  S.Score: 'Score',
  S.Selectstage: 'Select stage',
  S.Advancedstage: 'Advanced stage',
  S.ultimatechallenge: 'ultimate challenge',
  S.Challengefailed: 'Failed',
  S.Placementisabnormalpleaserearrange: 'Placement is abnormal, please rearrange',
  S.Giveupchallenge: 'quit',
  S.shareGame: 'share',
  S.Customchessgame: 'Custom chess game',
  S.reset: 'reset',
  S.Thischessgamehasnosolutionpleaserearrangethepieces: 'This chess game has no solution, please rearrange the pieces',
  S.Thischessgameiscompletedpleaserearrange: 'This chess game is completed, please rearrange',
  S.Practicerecord: 'Practice record',
  S.infinitestages: 'infinite stages',
  S.Win: 'Win',
  S.next: 'next',
  S.youcantgetstarswithAItutorialcontinue: "you can't get stars with AI tutorial, continue?",
  S.remaining: 'Remaining',
  S.Tutorialcompleted: 'Tutorial completed',
  S.restart: 'restart',
  S.stagerecords: 'stage records',
  S.Invitation: 'Friend invitation',
  S.stageprogress: 'stage progress',
  S.Inviting: 'Inviting',
  S.hasdeclined: 'has declined',
  S.Start: 'Start',
  S.Waitingforfriendtostart: 'Waiting for friend to start',
  S.Gamehasntstartedleavetheroom: "Game hasn't started, leave the room?",
  S.Matching: 'Matching...',
  S.Esimatedtime: 'Esimated time',
  S.seconds: 's',
  S.matchfound: 'match found',
  S.startingthegame: 'starting the game',
  S.hasquitrematch: 'opponent has quit, rematch?',
  S.hasquit: 'opponent has quit',
  S.Rematch: 'Rematch',
  S.placement: 'placement',
  S.observation: 'observation',
  S.Observing: 'Observing',
  S.Placing: 'Placing',
  S.solving: 'solving',
  S.waitfortocompletethegame: 'wait for opponent to complete the game',
  S.time: 'time',
  S.solvemoves: 'moves',
  S.Playagain: 'Play again',
  S.timeout: 'timeout',
  S.failurewithoutfinishStillquit:
      'It will be considered a failure if you quit without finishing the game. Still quit?',
  S.Reconnecting: 'Reconnecting',
  S.vsrecords: '1 vs 1 records',
  S.Winloss: 'Win/loss',
  S.stage3x3: '3 x 3 stage',
  S.stage4x4: '4 x 4 stage',
  S.minsago: ' mins ago ',
  S.hrsago: ' hrs ago',
  S.Stage: 'Stage',
  S.dengji: 'stage',
  S.replayplayback: 'Replay',
  S.Norecords: 'No records',
  S.Nofriends: 'No friends',
  S.Play: 'Go to play',
  S.Forbeginners: 'For beginners',
  S.Joindiscussion: 'Join',
  S.closeTutorial: 'close',
  S.DeviceInformation: 'Device Information',
  S.DeviceType: 'Device Type',
  S.Model: 'Model',
  S.update: 'update',
  S.infinite: 'infinite',
  S.Lv: 'Lv. %s',
  S.stageprogresoverwrittenunlockedlevel:
      'The %s stage progress will be overwritten after sync, You will be unlocked to level %s',
  S.PlaywithGANKlotski: 'Play with GAN Klotski',
  S.PlaywithoutGANKlotski: 'Play without GAN Klotski',
  S.gamedonotfinish: 'game do not finish',
  S.Connecting: 'Connecting',
  S.Donotfinished: 'Do not finished',
  S.Offline: 'Offline',
  S.Countdown: 'Countdown',
  S.Waiting: 'Waiting',
  S.Locked: 'Locked',
  S.connectsmartdeviceunlockVS: 'Please connect the "Klotski" smart device first to unlock the 1 VS 1 function.',
  S.chessCompleted: 'Completed',
  S.knowresultstillquite: 'You will know the result after the opponent has finished, still quit?',
  S.Networkissuepleaseretrylater: 'Network issue, please retry later',
  S.Failedcompletegameinspecifiedtime: 'Failure to restore the chess game within the defined time',
  S.interruptinvitation: 'Closing the interface will interrupt the invitation, continue?',
  S.friendInviting: 'Inviting',
  S.resolving: 'resolving',
  S.placethepiecesfirst: 'Place the pieces first',
  S.Networkissue: 'Network issue',
  S.Refresh: 'Refresh',
  S.Doubleclickchesstoremove: 'Double-click on a chess piece within the chessboard to remove it',
  S.Connected: 'Connected',
  S.Devicenotfound: 'Device not found',
  S.Quitgame: 'Quit',
  S.Random: 'Random',
  S.ShareScore: 'Share',
  S.StageCompleted: 'Completed',
  S.Gamedonotfinishstillquite: 'Game do not finish, still quit?',
  S.WaitUnLocked: 'Locked',
  S.Downloading: 'Downloading',
  S.Downloaded: 'Downloaded',
  S.gamenotoverregeneratenewgame: 'The game is not over. Do you want to regenerate a new game?',
  S.Selectdate: 'Select date',
  S.Pleaseoperatesmartdevice: 'Please operate with a smart device',
  S.Reachedmaximumlevel: 'Reached the maximum level',
  S.disconnectotherdevicesfirst: 'Please disconnect other devices first',
  S.UpdateruleseveryMondayupdatedata:
      'The weekly leaderboard data is calculated from 08:00:00 on Monday to 07:59:59 next Monday in UTC time. The scores of the previous week\'s leaderboard are settled at 08:00:00 every Monday. \n\nThe ranking rules for the leaderboard are as follows:\n1. Ranking is based on clearance time, with shorter times resulting in higher rankings.\n2. In cases where clearance times are the same, ranking is based on the number of steps taken, with fewer steps resulting in higher rankings.\n3. If clearance times and the number of steps are both the same, ranking is based on the time of making it onto the leaderboard, with earlier times resulting in higher rankings.',
  S.UpdateruleseveryMondayupdatedataCHN:
      'The weekly ranking data is calculated from Monday 00:00:00 to Sunday 23:59:59 Beijing time. Each Monday at 00:00:00, the results of the previous week\'s ranking are calculated. \n\nThe ranking rules are as follows:\n1. Ranking is based on clearance time, with shorter times resulting in higher rankings.\n2. In cases where clearance times are the same, ranking is based on the number of steps taken, with fewer steps resulting in higher rankings.\n3. If clearance times and the number of steps are both the same, ranking is based on the time of making it onto the leaderboard, with earlier times resulting in higher rankings.',
  S.CST: 'CST',
  S.EDT: 'EDT',
  S.Notonlist: 'Not on the list',
  S.Thisweek: 'This week',
  S.rankinglist: 'ranking list',
  S.UnderAITeachingnotgetscore: 'Under the AI Teaching, you will not be able to get a score. Are you sure to continue?',
  S.timesisuseduptoday: 'The limited number of times is used up today',
  S.Youhavenchanceslefttoday: 'You have %s chances left today',
  S.ChallengeSettlement: 'Challenge Settlement',
  S.BrandName: 'Brand name',
  S.DeviceModel: 'Device Model',
  S.BluetoothAddress: 'Bluetooth Address',
  S.ProductName: 'Product name',
  S.Username: 'Username',
  S.UploadingPleaseWait: 'Uploading, please wait',
  S.StartChallenge: 'Start',
  S.Timehasrunout: 'Time has run out',
  S.Outofmoves: 'Out of moves.',
  S.OnlyNstepsawayfromsolving: 'Only %s steps away from solving the chess game',
  S.Congratulationsonsolvingthechessgame:
      'Congratulations on solving the chess game. Come and try challenging yourself',
  S.Basicinstructions: 'Basic instructions',
  S.Solutionapproach: 'Solution approach',
  S.Rules: 'Rules',
  S.HowtoPlay: 'How to Play',
  S.Modes: 'Modes',
  S.Results: 'Results',
  S.CommonTerminology: 'Common Terminology',
  S.SharingandLearning: 'Sharing and Learning',
  S.RulesDetail:
      'By moving the various pieces, help the large square move from its initial position to the center of the bottom of the board. It is not allowed to cross over any of the pieces during the movement, and successfully completing the challenge constitutes passing the level.',
  S.HowtoPlayDetail:
      'Hold the block that needs to be moved and slide it in any direction. The timer starts as soon as the movement begins. For players with devices, they need to connect their device first, set up the chessboard according to the device\'s instructions, and then press the confirmation key to start the timer.',
  S.ModesDetail:
      'Classic: This mode will periodically update with new levels, releasing 9 levels each time. After the update, the original 9 levels will be overwritten, and players can check the leaderboard for the previous levels by switching the time period.\n\nStages: Players can challenge the levels in order, and earn 1-3 stars based on their completion time.\n\nPractice: Players can choose a difficulty level from 1-13, and the system will generate corresponding chessboards. If players encounter difficulties during practice, they can click on the intelligent teaching option to follow AI learning.\n\n1 VS 1: Players can choose a difficulty level from 1-13 and select to automatically match with other players or invite friends to play together. If they choose automatic matching, the system will match them with players of similar difficulty levels. If they choose to invite friends, there are no device connection restrictions.',
  S.ResultsDetail:
      'Time: The time taken to complete the game.\nSteps: Moving each block one square counts as one step.',
  S.CommonTerminologyDetail:
      'tps: The number of steps moved per second, which is calculated by dividing the number of steps by the time in seconds. For example, tps1.20 means moving 1.2 steps per second.\n\nsubX: A score below X, usually referring to the time score (in seconds) or the number of steps score. For example, sub3 means a score below 3 seconds.',
  S.SharingandLearningDetail:
      'If players cannot pass certain levels, they can go to the "Beginners Group" to ask for help.',
  S.SharingandLearningDetail2:
      'For those who want to learn more about the science of Klotski, they can go to the "Science Group" to exchange and learn.',
  S.SharingandLearningDetail3:
      'If players want to know more about the solutions to classic Klotski levels, they can go to the "Classic Group" to exchange and learn.',
  S.RulesDetailNum:
      'Move the blocks to arrange them in order from left to right and top to bottom, with numbers increasing from 1 to 8 or 1 to 15.',
  S.HowtoPlayDetailNum:
      'Press and hold the block you want to move and slide it in any direction. The timer starts when you start sliding. For players using devices, connect to the device first, set up the puzzle as prompted, press confirm, and then start sliding to start the timer.',
  S.ModesDetailNum:
      '3 x 3 Stage: Slide the number blocks within a 3x3 area. Arrange the numbers 1-8 in order from left to right and top to bottom. Earn 1-3 stars based on your completion time.\n\n4 x 4 Stage: Slide the number blocks within a 4x4 area. Arrange the numbers 1-15 in order from left to right and top to bottom. Earn 1-3 stars based on your completion time.\n\nPractice: Players can select the difficulty level of either 3x3 or 4x4 and the system will generate a corresponding puzzle. If you encounter difficulties during practice, click on intelligent teaching to follow AI learning.\n\n1 VS 1: Players can choose the difficulty level of either 3x3 or 4x4 and select automatic matching or invite friends to play. If you select automatic matching, the system will match you with players of the same difficulty level. If you choose to invite friends, you can play together without device connection limitations.',
  S.ResultsDetailNum: 'Time: The time taken to complete the game.\nSteps: Each move of a block counts as one step.',
  S.CommonTerminologyDetailNum:
      '8p/15p/24p: Refers to the three-stage/four-stage/five-stage...numbered Rush Hour puzzles.\n\ntps: The number of steps moved per second, calculated by steps divided by seconds. For example, tps1.20 means moving 1.2 steps per second.\n\nsubX: Completion time below X. Usually refers to single-time completion results in seconds or steps. For example, sub3 means completing the task in under 3 seconds.',
  S.SharingandLearningDetailNum:
      'If you encounter difficulties in passing a level, you can go to the 【Number Puzzle Group】 to post for help.',
  S.HrdTeachTitle: 'Beginner\'s Guide to Klotski',
  S.NumTeachTitle: 'Beginner\'s Guide to Number Puzzle',
  S.ContactUs: 'Contact Us',
  S.ContactUsDetail:
      'If you encounter any issues while using the app, you can post your feedback in the group or scan the QR code to add "方块仔" for feedback',
  S.LookTeach: 'View Instruction',
  S.Time: 'Time',
  S.Numberofvictories: 'Wins This Week',
  S.Winrate: 'Win rate',
  S.Smartdeviceplayer: 'Smart device player',
  S.Ready: 'Ready',
  S.Prepare: 'Prepare',
  S.Thedevicehasbeendisconnected: 'Device Disconnected',
  S.ProceedtoConnect: 'Proceed to Connect',
  S.Settings: 'Settings',
  S.ConnectKlotski: 'Connect Klotski',
  S.DeviceConnected: 'Connected',
  S.VSSettings: '1 VS 1 Settings',
  S.MatchSmartdeviceplayer: 'Match Smart device player',
  S.Waitingforfriendtoready: 'Waiting for friend to ready',
  S.Follow: 'Follow',
  S.Applied: 'Applied',
  S.Thenumberofslidespersecond: 'Slides per second is crucial for gauging speed proficiency in Klotski',
  S.Unknownlocation: 'Unknown location',
  S.Solutiondiscussion: 'Solution Discussion',
  S.Goto: 'Proceed',
  S.FamousGameSlogan: 'Conquer the Three Kingdoms to top the Leaderboard',
  S.FreeGameSlogan: 'Practise more for quicker level clears',
  S.LevelGameSlogan: 'Conquer challenging levels and collect a galaxy of stars',
  S.LevelNumGameSlogan: 'Conquer levels and collect stars',
  S.RankGameSlogan: 'Invite your friends and play together',
  S.Checkthetutorialguideassistance: 'Check the tutorial guide for assistance',
  S.ThesolutionapproachforDifficultyN:
      'The solution approach for "Difficulty %s" has been unlocked. Would you like to go and check it out?'
};
