import 'intl_keys.dart';

const hk_HK_res = {
  S.OK: '確定',
  S.Next: '下一步',
  S.Cancel: '取消',
  S.Connect: '連接',
  S.Dis: '中斷連線',
  S.Disconnect: '中斷連線',
  S.Devicenotconnected: '未連接裝置',
  S.Klotski: '華容道',
  S.NumberPuzzle: '數字華容道',
  S.Classic: '經典',
  S.Practice: '練習',
  S.Stages: '關卡',
  S.VS: '一對一',
  S.Devices: '裝置',
  S.Search: '搜尋',
  S.Searching: '正在搜尋',
  S.Searchagain: '再次搜尋',
  S.Battery: '電池',
  S.Switch: '開關',
  S.FirmwareVersion: '韌體版本',
  S.Bluetoothnotenabled: '未啟用藍牙',
  S.Enablebluetooth: '啟用藍牙',
  S.Renamedevice: '重新命名裝置',
  S.Disconnectdevice: '將裝置中斷連線',
  S.FirmwareUpgrade: '韌體升級',
  S.Upgradefirmwareto: '將韌體升級至',
  S.FirmwareupgradingPleasedonotclosetheapp: '正在升級韌體，請勿關閉應用程式',
  S.Customize: '自訂',
  S.SlideTime: '滑動和時間',
  S.AITutorial: 'AI 教學',
  S.StageSync: '關卡同步',
  S.syncappdevicestageprogress: '智慧型裝置關卡進度與應用程式不同。是否要同步？',
  S.Sync: '同步',
  S.Records: '紀錄',
  S.Invite: '邀請',
  S.Move: '步數',
  S.PreviousStep: '上一步',
  S.Speed: ' x',
  S.Puttingoneselfinsomeoneelsesshoes: '換位思考',
  S.ThreeHeroesSwearBrotherhoodInThePeachGarden: '桃園三結義',
  S.FuXisEightTrigramsWaterKanTrigram: '伏羲八卦.水水坎',
  S.PassFiveLevels: '通過五關',
  S.Domineeringandtyrannical: '橫行霸道',
  S.TheThreeBrothersFightAgainstLuBu: '三英戰呂布',
  S.Drawingaswordandmountingahorse: '橫刀立馬',
  S.LiuBeiPaysThreeVisitsToZhugeLiangscottage: '三顧茅廬',
  S.Settingfiretotheconnectedcamps: '火燒連營',
  S.Devicenamemodifiedsuccessfully: '已完成',
  S.Failed: '失敗',
  S.FirmwareUpdateSuccessfully: '韌體更新成功',
  S.Back: '返回',
  S.Newrecord: '新紀錄',
  S.Noscore: '無分數',
  S.PleaseselecttheStageyouwanttosync: '請選擇要同步的關卡',
  S.GANKlotski: 'GAN 華容道',
  S.Inprogress: '正在進行',
  S.SyncCompleted: '已完成',
  S.automatching: '自動配對',
  S.Recommendedstage: '建議關卡',
  S.selectachessgame: '選擇棋局',
  S.quit: '退出',
  S.Completed: '已完成',
  S.pressOKafterplacingthepieces: '放置棋子後請按「確定」',
  S.recordofClassic: '經典紀錄',
  S.Chessgame: '棋局',
  S.moves: '步數',
  S.Score: '分數',
  S.Selectstage: '選擇關卡',
  S.Advancedstage: '進階關卡',
  S.ultimatechallenge: '終極挑戰',
  S.Challengefailed: '失敗',
  S.Placementisabnormalpleaserearrange: '位置異常，請重新排列',
  S.Giveupchallenge: '退出',
  S.shareGame: '分享',
  S.Customchessgame: '自訂棋局',
  S.reset: '重設',
  S.Thischessgamehasnosolutionpleaserearrangethepieces: '此棋局無解，請重新排列棋子',
  S.Thischessgameiscompletedpleaserearrange: '已完成此棋局，請重新排列',
  S.Practicerecord: '練習紀錄',
  S.infinitestages: '無限關卡',
  S.Win: '獲勝',
  S.next: '下一關',
  S.youcantgetstarswithAItutorialcontinue: '使用 AI 教學無法獲得星星，是否繼續？',
  S.remaining: '剩餘',
  S.Tutorialcompleted: '已完成教學',
  S.restart: '重新開始',
  S.stagerecords: '關卡紀錄',
  S.Invitation: '好友邀請',
  S.stageprogress: '關卡狀態',
  S.Inviting: '正在邀請',
  S.hasdeclined: '已拒絕',
  S.Start: '開始',
  S.Waitingforfriendtostart: '正在等待好友開始',
  S.Gamehasntstartedleavetheroom: '遊戲尚未開始，是否離開房間？',
  S.Matching: '正在配對...',
  S.Esimatedtime: '估計時間',
  S.seconds: '秒',
  S.matchfound: '找到配對',
  S.startingthegame: '正在開始遊戲',
  S.hasquitrematch: '對手已退出，是否重新配對？',
  S.hasquit: '對手已退出',
  S.Rematch: '重新配對',
  S.placement: '放置',
  S.observation: '觀察',
  S.Placing: '正在放置',
  S.Observing: '正在觀察',
  S.solving: '正在遊玩',
  S.waitfortocompletethegame: '等待對手完成遊戲',
  S.time: '時間',
  S.solvemoves: '步數',
  S.Playagain: '再玩一次',
  S.timeout: '逾時',
  S.failurewithoutfinishStillquit: '如果退出而未完成遊戲，將視為失敗。是否仍要退出？',
  S.Reconnecting: '正在重新連線',
  S.vsrecords: '一對一紀錄',
  S.Winloss: '勝／敗',
  S.stage3x3: '3 x 3 關卡',
  S.stage4x4: '4 x 4 關卡',
  S.minsago: '分鐘前',
  S.hrsago: '小時前',
  S.Stage: '難度',
  S.dengji: '關卡',
  S.replayplayback: '複盤播放',
  S.Norecords: '無紀錄',
  S.Nofriends: '還沒有好友',
  S.Play: '去玩',
  S.Forbeginners: '適合初學者',
  S.Joindiscussion: '加入',
  S.closeTutorial: '關閉',
  S.DeviceInformation: '裝置資訊',
  S.DeviceType: '裝置類型',
  S.Model: '型號',
  S.update: '更新',
  S.infinite: '無限',
  S.Lv: '第%s關',
  S.stageprogresoverwrittenunlockedlevel: '同步後將覆蓋%s關卡進度，將解鎖至第%s關',
  S.PlaywithGANKlotski: '使用 GAN 華容道遊玩',
  S.PlaywithoutGANKlotski: '不使用 GAN 華容道遊玩',
  S.gamedonotfinish: '遊戲未完成',
  S.Connecting: '正在連線',
  S.Donotfinished: '未完成',
  S.Offline: '離線',
  S.Countdown: '倒數計時',
  S.Waiting: '等待中',
  S.Locked: '已鎖定',
  S.connectsmartdeviceunlockVS: '請先連接「華容道」智慧型裝置以解鎖一對一功能。',
  S.chessCompleted: '已完成',
  S.knowresultstillquite: '您將在對方完成後知道結果，是否仍要退出？',
  S.Networkissuepleaseretrylater: '網路問題，請稍後重試',
  S.Failedcompletegameinspecifiedtime: '未能在規定時間內復原棋局',
  S.interruptinvitation: '關閉介面將中斷邀請，是否繼續？',
  S.friendInviting: '好友邀請中',
  S.resolving: '破解',
  S.placethepiecesfirst: '請先放置棋子',
  S.Networkissue: '網路問題',
  S.Refresh: '重新整理',
  S.Doubleclickchesstoremove: '按兩下棋盤內的棋子可加以移除',
  S.Connected: '已連線',
  S.Devicenotfound: '找不到裝置',
  S.Quitgame: '退出',
  S.Random: '隨機',
  S.ShareScore: '分享',
  S.StageCompleted: '已完成',
  S.Gamedonotfinishstillquite: '遊戲未完成，是否仍要退出？',
  S.WaitUnLocked: '已鎖定',
  S.Downloading: '正在下載',
  S.Downloaded: '已下載',
  S.gamenotoverregeneratenewgame: '遊戲尚未結束。是否要重新產生新遊戲？',
  S.Selectdate: '選擇日期',
  S.Pleaseoperatesmartdevice: '請使用智慧型裝置操作',
  S.Reachedmaximumlevel: '已達上限',
  S.disconnectotherdevicesfirst: '請先將其他裝置中斷連線',
  S.UpdateruleseveryMondayupdatedata:
      '周榜數據計算時間為UTC時間週一08:00:00-下週一07:59:59，每週一08:00:00結算上一週榜單成績。\n\n榜單排名規則如下：\n1、優先按照通關時間進行排名，即通關時間越短，排名越靠前；\n2、在通關時間相同的情況下，根據步數進行排名，即步數越少，排名越靠前；\n3、如通關時間和步數都相同，則按照上榜時間進行排序，即上榜時間越早，排名越靠前。',
  S.UpdateruleseveryMondayupdatedataCHN:
      '周榜數據計算時間為北京時間週一00:00:00至週日23:59:59，每週一凌晨00:00:00結算上一週榜單成績。\n\n榜單排名規則如下：\n1、優先按照通關時間進行排名，即通關時間越短，排名越靠前；\n2、在通關時間相同的情況下，根據步數進行排名，即步數越少，排名越靠前；\n3、如通關時間和步數都相同，則按照上榜時間進行排序，即上榜時間越早，排名越靠前。',
  S.CST: '北京時間',
  S.EDT: '紐約時間',
  S.Notonlist: '未上榜',
  S.Thisweek: '本週',
  S.rankinglist: '排行榜',
  S.UnderAITeachingnotgetscore: '在 AI 教學下，將無法獲得分數。是否確定要繼續？',
  S.timesisuseduptoday: '今日已用完有限次數',
  S.Youhavenchanceslefttoday: '今日剩餘 %s 次機會',
  S.ChallengeSettlement: '挑戰結算',
  S.BrandName: '品牌名稱',
  S.DeviceModel: '裝置型號',
  S.BluetoothAddress: '藍牙位址',
  S.ProductName: '產品名稱',
  S.Username: '使用者名稱',
  S.UploadingPleaseWait: '記錄上傳中，請稍後',
  S.StartChallenge: '開始挑戰',
  S.Timehasrunout: '時間耗盡了',
  S.Outofmoves: '步數耗盡了',
  S.OnlyNstepsawayfromsolving: '太可惜了，距離解開棋局僅差%s步',
  S.Congratulationsonsolvingthechessgame: '恭喜你解開棋局，快來嘗試自己挑戰一下吧',
  S.Basicinstructions: '基礎說明',
  S.Solutionapproach: '解決方案思路',
  S.Rules: '規則',
  S.HowtoPlay: '操作方法',
  S.Modes: '模式',
  S.Results: '成績',
  S.CommonTerminology: '常見術語說明',
  S.SharingandLearning: '分享和學習',
  S.RulesDetail: '通過移動各個棋子，幫助大方塊從初始位置移到棋盤最下方中部，移動過程中不允許跨越棋子，“出逃”成功即為通關。',
  S.HowtoPlayDetail: '按住需要移動的方塊，往任意方向滑動，滑動開始則計時開始。有設備的玩家，需要先連接設備，按照設備提示擺放好棋局後，按確認鍵後滑動開始則計時開始。',
  S.ModesDetail:
      '經典：該模式會不定期更新全新關卡，每次更新釋放9關，更新後原9關關卡被覆蓋，玩家可通過切換榜單時間，查看原關卡的上榜成績。\n\n關卡：玩家可按關卡順序，一路闖關挑戰，每局根據通關時間，獲得1-3顆星星。\n\n練習：玩家可選擇1-13的難度，系統自动生成對應難度的棋局，如在練習過程中遇到困難，可點擊智能教學跟隨AI學習。\n\n一對一：玩家可選擇1-13的難度，可選擇自動匹配或邀請好友對戰。如選擇了自動匹配，系統會根據設備情況，自動匹配選擇了同等難度的玩家一起對戰，如選擇好友邀請，則可邀請站內好友一起對戰，不受設備連接限制。',
  S.ResultsDetail: '時間：完成遊戲所用的時間 \n步數：每個方塊移動一格記為一步',
  S.CommonTerminologyDetail:
      'tps：每秒移動的步數，即步數除以秒為單位的時間。如tps1.20，即表示每秒移動1.2步。\n\nsubX：成績在X以下，一般指的是描述單次時間成績（單位為秒）或者單次步數成績（單位為步）。如sub3，可表示成績在3秒以內。',
  S.SharingandLearningDetail: '遇到關卡無法通關，可前往【華容道新手交流小組】發帖求助；',
  S.SharingandLearningDetail2: '想了解更多華容道棋局科普內容，可前往【華容道科普小組】進行交流學習；',
  S.SharingandLearningDetail3: '想了解華容道經典名局相關解法，可前往【經典名局交流小組】進行交流學習。',
  S.RulesDetailNum: '移動方塊，將方塊按從左到右、從上到下、從小到大的順序排序。',
  S.HowtoPlayDetailNum: '按住需要移動的方塊，往任意方向滑動，滑動開始則計時開始。有設備的玩家，需要先連接設備，按照設備提示擺放好棋局後，按確認鍵後滑動開始則計時開始。',
  S.ModesDetailNum:
      '3 x 3 關卡：數字方塊限定在3×3的區域內滑動，將1-8的數字方塊按從左到右、從上到下、從小到大的順序排序，根據通關時間，獲得1-3顆星星。\n\n4 x 4 關卡：數字方塊限定在4×4的區域內滑動，將1-15的數字方塊按從左到右、從上到下、從小到大的順序排序，根據通關時間，獲得1-3顆星星。\n\n練習：玩家可選擇3×3、4×4的難度，系統自动生成對應難度的棋局，如在練習過程中遇到困難，可點擊智能教學跟隨AI學習。\n\n一對一：玩家可選擇3×3、4×4的難度，可選擇自動匹配或邀請好友對戰。如選擇了自動匹配，系統會根據設備情況，自動匹配選擇了同等難度的玩家一起對戰，如選擇好友邀請，則可邀請站內好友一起對戰，不受設備連接限制。',
  S.ResultsDetailNum: '時間：完成遊戲所用的時間\n步數：每個方塊移動一格記為一步',
  S.CommonTerminologyDetailNum:
      '8p/15p/24p......：分別指代三階/四階/五階......的數字華容道。\n\ntps：每秒移動的步數，即步數除以秒為單位的時間。如tps1.20，即表示每秒移動1.2步。\n\nsubX：成績在X以下，一般指的是描述單次時間成績（單位為秒）或者單次步數成績（單位為步）。如sub3，可表示成績在3秒以內。',
  S.SharingandLearningDetailNum: '遇到關卡無法通關，可前往【數字華容道新手小組】發帖求助。',
  S.HrdTeachTitle: '華容道新手指引',
  S.NumTeachTitle: '數字華容道新手指引',
  S.ContactUs: '聯繫我們',
  S.ContactUsDetail: '在APP使用上遇到問題，您可在小組發帖反饋，也可掃碼添加方塊仔進行反饋',
  S.LookTeach: '查看教學',
  S.Time: '時間',
  S.Numberofvictories: '本週勝局數',
  S.Winrate: '勝率',
  S.Smartdeviceplayer: '智能設備玩家',
  S.Ready: '已準備',
  S.Prepare: '準備',
  S.Thedevicehasbeendisconnected: '裝置中斷連線',
  S.ProceedtoConnect: '前往連接',
  S.Settings: '設定',
  S.ConnectKlotski: '連接裝置',
  S.DeviceConnected: '已連線',
  S.VSSettings: '一對一設定',
  S.MatchSmartdeviceplayer: '配對智能設備玩家',
  S.Waitingforfriendtoready: '正在等待好友準備',
  S.Follow: '關注',
  S.Applied: '已套用',
  S.Thenumberofslidespersecond: '每秒滑動次數，是衡量華容道手速水平的一個重要參數',
  S.Unknownlocation: '未知位置',
  S.Solutiondiscussion: '解法探討',
  S.Goto: '前往',
  S.FamousGameSlogan: '闖三國，衝榜單',
  S.FreeGameSlogan: '勤練習，爆速快',
  S.LevelGameSlogan: '衝千關，集星星',
  S.LevelNumGameSlogan: '衝關卡，集星星',
  S.RankGameSlogan: '邀朋友，一同玩',
  S.Checkthetutorialguideassistance: '查看教程指南，尋求幫助',
  S.ThesolutionapproachforDifficultyN: '【难度%s】解法思路已解锁，是否前往查看？'
};
