import 'intl_keys.dart';

const de_DE_res = {
  S.OK: 'OKAY',
  S.Next: 'Nächster',
  S.Cancel: 'Abbrechen',
  S.Connect: 'Verbinden',
  S.Dis: 'Trennen',
  S.Disconnect: 'Trennen',
  S.Devicenotconnected: 'Gerät nicht angeschlossen',
  S.Klotski: 'Klotski',
  S.NumberPuzzle: 'Zahlen-Rätsel',
  S.Classic: 'Klassisch',
  S.Practice: 'Übung',
  S.Stages: 'Bühnen',
  S.VS: '1 GEGEN 1',
  S.Devices: 'Geräte',
  S.Search: 'Suchen',
  S.Searching: 'Suche',
  S.Searchagain: 'Erneute Suche',
  S.Battery: 'Batterie',
  S.Switch: 'Schalter',
  S.FirmwareVersion: 'Firmware-Version',
  S.Bluetoothnotenabled: 'Bluetooth nicht aktiviert',
  S.Enablebluetooth: 'Aktivieren Sie Bluetooth',
  S.Renamedevice: 'Gerät umbenennen',
  S.Disconnectdevice: 'Gerät trennen',
  S.FirmwareUpgrade: 'Firmware-Aktualisierung',
  S.Upgradefirmwareto: 'Aktualisieren Sie die Firmware auf',
  S.FirmwareupgradingPleasedonotclosetheapp: 'Firmware-Upgrade, Bitte schließen Sie die App nicht',
  S.Customize: 'Anpassen',
  S.SlideTime: 'Folie & Zeit',
  S.AITutorial: 'KI-Tutorial',
  S.StageSync: 'Bühnen-Synchronisierung',
  S.syncappdevicestageprogress:
      'Der Phasenfortschritt Ihres Smartgeräts ist nicht derselbe wie der der App. Möchten Sie sie synchronisieren?',
  S.Sync: 'Synchronisieren',
  S.Records: 'Aufzeichnungen',
  S.Invite: 'Einladen',
  S.Move: 'Bewegt',
  S.PreviousStep: 'Vorheriger Schritt',
  S.Speed: ' x',
  S.Puttingoneselfinsomeoneelsesshoes: 'Sich in die Lage eines anderen versetzen',
  S.ThreeHeroesSwearBrotherhoodInThePeachGarden: 'Drei Helden schwören Brüderlichkeit im Pfirsichgarten',
  S.FuXisEightTrigramsWaterKanTrigram: 'Fu Xis Acht Trigramme: Wasser Kan Trigramm',
  S.PassFiveLevels: 'Bestehen Sie fünf Levels',
  S.Domineeringandtyrannical: 'Herrschsüchtig und tyrannisch',
  S.TheThreeBrothersFightAgainstLuBu: 'Die drei Brüder kämpfen gegen Lu Bu',
  S.Drawingaswordandmountingahorse: 'Ein Schwert ziehen und auf ein Pferd steigen',
  S.LiuBeiPaysThreeVisitsToZhugeLiangscottage: 'Liu Bei besucht Zhuge Liangs Hütte dreimal',
  S.Settingfiretotheconnectedcamps: 'Die miteinander verbundenen Lager in Brand setzen',
  S.Devicenamemodifiedsuccessfully: 'Abgeschlossen',
  S.Failed: 'Misslungen',
  S.FirmwareUpdateSuccessfully: 'Firmware-Update erfolgreich',
  S.Back: 'Zurück',
  S.Newrecord: 'Neuer Rekord',
  S.Noscore: 'Keine Partitur',
  S.PleaseselecttheStageyouwanttosync: 'Bitte wählen Sie die Bühne aus, die Sie synchronisieren möchten',
  S.GANKlotski: 'GAN Klotski',
  S.Inprogress: 'Im Gange',
  S.SyncCompleted: 'Abgeschlossen',
  S.automatching: 'Automatischer Abgleich',
  S.Recommendedstage: 'Empfohlene Etappe',
  S.selectachessgame: 'Wählen Sie eine Schachpartie',
  S.quit: 'Verlassen',
  S.Completed: 'Abgeschlossen',
  S.pressOKafterplacingthepieces: 'Drücken Sie "OK", nachdem Sie die Teile platziert haben',
  S.recordofClassic: 'Rekord der Klassik',
  S.Chessgame: 'Schachspiel',
  S.moves: 'Bewegt',
  S.Score: 'Punktzahl',
  S.Selectstage: 'Bühne auswählen',
  S.Advancedstage: 'Fortgeschrittenes Stadium',
  S.ultimatechallenge: 'Ultimative Herausforderung',
  S.Challengefailed: 'Misslungen',
  S.Placementisabnormalpleaserearrange: 'Die Platzierung ist abnormal, bitte neu arrangieren',
  S.Giveupchallenge: 'Verlassen',
  S.shareGame: 'Freigeben',
  S.Customchessgame: 'Benutzerdefiniertes Schachspiel',
  S.reset: 'Zurücksetzen',
  S.Thischessgamehasnosolutionpleaserearrangethepieces:
      'Dieses Schachspiel hat keine Lösung, bitte ordnen Sie die Figuren neu an',
  S.Thischessgameiscompletedpleaserearrange: 'Diese Schachpartie ist beendet, bitte neu anordnen',
  S.Practicerecord: 'Praxis-Bilanz',
  S.infinitestages: 'Unendliche Stufen',
  S.Win: 'Gewinnen',
  S.next: 'Nächster',
  S.youcantgetstarswithAItutorialcontinue: 'Du kannst mit dem KI-Tutorial keine Sterne bekommen, weitermachen?',
  S.remaining: 'Verbleibend',
  S.Tutorialcompleted: 'Tutorial abgeschlossen',
  S.restart: 'Neustarten',
  S.stagerecords: 'Bühnenrekorde',
  S.Invitation: 'Freundschaftseinladung',
  S.stageprogress: 'Status der Etappe',
  S.Inviting: 'Einladend',
  S.hasdeclined: ' ist zurückgegangen',
  S.Start: 'Anfangen',
  S.Waitingforfriendtostart: 'Warten auf den Start eines Freundes',
  S.Gamehasntstartedleavetheroom: 'Das Spiel hat noch nicht begonnen, den Raum verlassen?',
  S.Matching: 'Passend...',
  S.Esimatedtime: 'Simulierte Zeit ',
  S.seconds: ' s',
  S.matchfound: 'Übereinstimmung gefunden',
  S.startingthegame: 'Starten des Spiels',
  S.hasquitrematch: 'Gegner hat aufgehört, Rückkampf?',
  S.hasquit: 'Gegner hat aufgehört',
  S.Rematch: 'Revanche',
  S.placement: 'Platzierung',
  S.observation: 'Beobachtung',
  S.Placing: 'Einbau',
  S.Observing: 'Beobachtend',
  S.solving: 'Spielen',
  S.waitfortocompletethegame: 'Warten Sie, bis Gegner das Spiel abgeschlossen hat',
  S.time: 'Zeit',
  S.solvemoves: 'Bewegt',
  S.Playagain: 'Erneut spielen',
  S.timeout: 'Zeitüberschreitung',
  S.failurewithoutfinishStillquit:
      'Es wird als Misserfolg angesehen, wenn Sie das Spiel beenden, ohne das Spiel zu beenden. Hören Sie immer noch auf?',
  S.Reconnecting: 'Wiederherstellen',
  S.vsrecords: '1 vs.1 Historie',
  S.Winloss: 'Gewinn/Niederlage',
  S.stage3x3: '3 x 3 Stufen',
  S.stage4x4: '4 x 4 Stufen',
  S.minsago: ' m ago',
  S.hrsago: ' hrs ago',
  S.Stage: 'Schwierigkeitsgrad',
  S.dengji: 'Stufe',
  S.replayplayback: 'Erneut spielen',
  S.Norecords: 'Keine Einträge',
  S.Nofriends: 'Noch keine Freunde',
  S.Play: 'Spiel aufrufen',
  S.Forbeginners: 'Für Einsteiger',
  S.Joindiscussion: 'Verbinden',
  S.closeTutorial: 'Schließen',
  S.DeviceInformation: 'Geräteinformationen',
  S.DeviceType: 'Gerätetyp',
  S.Model: 'Gerätemodell',
  S.update: 'Update',
  S.infinite: 'Unendliche',
  S.Lv: 'Stufe %s',
  S.stageprogresoverwrittenunlockedlevel:
      'Der Fortschritt der %s-Phase wird nach der Synchronisierung überschrieben. Sie werden auf Stufe %s freigeschaltet',
  S.PlaywithGANKlotski: 'Spielen Sie mit GAN Klotski',
  S.PlaywithoutGANKlotski: 'Spielen Sie ohne GAN Klotski',
  S.gamedonotfinish: 'Das Spiel wird nicht beendet',
  S.Connecting: 'Verbindend',
  S.Donotfinished: 'Nicht fertig',
  S.Offline: 'Offline',
  S.Countdown: 'Countdown',
  S.Waiting: 'Warten',
  S.Locked: 'Verschlossen',
  S.connectsmartdeviceunlockVS:
      'Bitte verbinden Sie zuerst das Smart-Gerät "Klotski", um die 1-gegen-1-Funktion freizuschalten.',
  S.chessCompleted: 'Abgeschlossen',
  S.knowresultstillquite: 'Sie werden das Ergebnis wissen, nachdem der Gegner fertig ist, immer noch ganz?',
  S.Networkissuepleaseretrylater: 'Problema de red, vuelva a intentarlo más tarde',
  S.Failedcompletegameinspecifiedtime:
      'Wiederherstellung des Schachspiels innerhalb der definierten Zeit fehlgeschlagen',
  S.interruptinvitation: 'Durch das Schließen der Schnittstelle wird die Einladung unterbrochen, weiter?',
  S.friendInviting: 'Einladung',
  S.resolving: 'Beheben',
  S.placethepiecesfirst: 'Legen Sie die Teile zuerst',
  S.Networkissue: 'Netzwerkproblem',
  S.Refresh: 'Auffrischen',
  S.Doubleclickchesstoremove: 'Doppelklick auf ein Schachstück auf dem Schachbrett, um es zu entfernen',
  S.Connected: 'Verbunden',
  S.Devicenotfound: 'Gerät nicht gefunden',
  S.Quitgame: 'Verlassen',
  S.Random: 'Zufällig',
  S.ShareScore: 'Freigeben',
  S.StageCompleted: 'Abgeschlossen',
  S.Gamedonotfinishstillquite: 'Das Spiel wird nicht beendet, Hören Sie immer noch auf?',
  S.WaitUnLocked: 'Verschlossen',
  S.Downloading: 'Laden',
  S.Downloaded: 'Gedownloadet',
  S.gamenotoverregeneratenewgame: 'Das Spiel ist nicht vorbei. Möchtest du ein neues Spiel erstellen?',
  S.Selectdate: 'Datum wählen',
  S.Pleaseoperatesmartdevice: 'Bitte mit einem Smart-Gerät bedienen',
  S.Reachedmaximumlevel: 'Maximale Stufe erreicht',
  S.disconnectotherdevicesfirst: 'Bitte zunächst andere Geräte trennen',
  S.UpdateruleseveryMondayupdatedata:
      'Die wöchentlichen Ranglisten-Daten werden von 08:00:00 am Montag bis 07:59:59 am nächsten Montag in koordinierter Weltzeit berechnet. Die Ergebnisse der vorherigen Woche werden jeden Montag um 08:00:00 abgerechnet. \n\nDie Ranglistenregeln für die Bestenliste lauten wie folgt:\n1. Die Rangfolge basiert auf der Freigabezeit, wobei kürzere Zeiten zu höheren Platzierungen führen.\n2. In Fällen, in denen die Freigabezeiten gleich sind, erfolgt die Rangfolge auf der Grundlage der Anzahl der Schritte, wobei weniger Schritte zu höheren Platzierungen führen.\n3. Wenn die Freigabezeiten und die Anzahl der Schritte gleich sind, erfolgt die Rangfolge auf der Grundlage der Zeit, zu der sie in die Bestenliste aufgenommen wurden, wobei frühere Zeiten zu höheren Platzierungen führen.',
  S.UpdateruleseveryMondayupdatedataCHN:
      'Die wöchentlichen Ranglisten-Daten werden von Montag 00:00:00 bis Sonntag 23:59:59 Pekinger Zeit berechnet. Jeden Montag um 00:00:00 werden die Ergebnisse der Rangliste der Vorwoche berechnet. \n\nDie Ranglistenregeln lauten wie folgt:\n1. Die Rangfolge basiert auf der Freigabezeit, wobei kürzere Zeiten zu höheren Platzierungen führen.\n2. In Fällen, in denen die Freigabezeiten gleich sind, erfolgt die Rangfolge auf der Grundlage der Anzahl der Schritte, wobei weniger Schritte zu höheren Platzierungen führen.\n3. Wenn die Freigabezeiten und die Anzahl der Schritte gleich sind, erfolgt die Rangfolge auf der Grundlage der Zeit, zu der sie in die Bestenliste aufgenommen wurden, wobei frühere Zeiten zu höheren Platzierungen führen.',
  S.CST: 'CST',
  S.EDT: 'EDT',
  S.Notonlist: 'Nicht in der Liste',
  S.Thisweek: 'Diese Woche',
  S.rankinglist: 'Rangliste',
  S.UnderAITeachingnotgetscore: 'Bei KI-Unterricht können Sie keine Punktzahl erzielen. Wirklich fortfahren?',
  S.timesisuseduptoday: 'Die begrenzte Anzahl ist für heute aufgebraucht',
  S.Youhavenchanceslefttoday: 'Du hast heute noch %s Versuche',
  S.ChallengeSettlement: 'Herausforderungsvereinbarung',
  S.BrandName: 'Markenname',
  S.DeviceModel: 'Gerätemodell',
  S.BluetoothAddress: 'Bluetooth-Adresse',
  S.ProductName: 'Produktname',
  S.Username: 'Nutzername',
  S.UploadingPleaseWait: 'Hochladen, bitte warten Sie',
  S.StartChallenge: 'Anfangen',
  S.Timehasrunout: 'Die Zeit ist abgelaufen',
  S.Outofmoves: 'Keine Züge mehr übrig',
  S.OnlyNstepsawayfromsolving: 'Nur noch %s Schritte entfernt, um das Schachspiel zu lösen',
  S.Congratulationsonsolvingthechessgame:
      'Herzlichen Glückwunsch zur Lösung des Schachspiels. Versuchen Sie doch mal, sich selbst herauszufordern.',
  S.Basicinstructions: 'Grundlegende Anweisungen',
  S.Solutionapproach: 'Lösungsansatz',
  S.Rules: 'Regeln',
  S.HowtoPlay: 'Bedienung',
  S.Modes: 'Modi',
  S.Results: 'Leistungen',
  S.CommonTerminology: 'Häufig verwendete Begriffe',
  S.SharingandLearning: 'Teilen und Lernen',
  S.RulesDetail:
      'Durch Bewegen der verschiedenen Spielsteine hilft man dem großen Block, sich von der Startposition zum mittleren unteren Teil des Spielbretts zu bewegen. Es ist nicht erlaubt, über andere Spielsteine zu springen. Das "Entkommen" aus der Situation bedeutet das erfolgreiche Beenden des Levels.',
  S.HowtoPlayDetail:
      'Halte den zu bewegenden Block gedrückt und schiebe ihn in eine beliebige Richtung. Die Zeit beginnt zu laufen, sobald die Bewegung gestartet wird. Spieler mit einem Gerät müssen zunächst ihr Gerät verbinden, das Spielbrett entsprechend den Anweisungen auf dem Gerät platzieren und dann die Bestätigungstaste drücken, um die Bewegung zu starten.',
  S.ModesDetail:
      'Klassisch: Dieser Modus wird regelmäßig mit neuen Levels aktualisiert. Bei jedem Update werden 9 neue Levels veröffentlicht und die vorherigen 9 Levels werden überschrieben. Spieler können durch Wechseln der Bestenliste die Highscores der vorherigen Levels einsehen.\n\nBühnen: Spieler können die Levels nacheinander durchspielen und herausgefordert werden. Je nach Abschlusszeit erhält man 1-3 Sterne.\n\nÜbung: Spieler können den Schwierigkeitsgrad von 1 bis 13 wählen. Das System generiert automatisch ein passendes Level für den gewählten Schwierigkeitsgrad. Wenn man während des Trainings auf Schwierigkeiten stößt, kann man auf die KI-gesteuerte Lernfunktion klicken, um vom AI-Ansatz zu lernen.\n\n1 GEGEN 1: Spieler können den Schwierigkeitsgrad von 1 bis 13 wählen und entweder automatisch einen Gegner suchen oder Freunde zu einem Duell einladen. Bei der automatischen Suche wird basierend auf den Geräteinformationen ein Gegner mit ähnlichem Schwierigkeitsgrad gefunden. Bei der Einladung von Freunden ist man nicht auf die Geräteverbindung beschränkt.',
  S.ResultsDetail:
      'Zeit: Die Zeit, die benötigt wurde, um das Spiel zu beenden.\nSchritte: Jede Bewegung eines Blocks zählt als ein Schritt.',
  S.CommonTerminologyDetail:
      'tps: Schritte pro Sekunde, d.h. die Anzahl der Schritte geteilt durch die Zeit in Sekunden. Zum Beispiel bedeutet tps1.20, dass 1,2 Schritte pro Sekunde gemacht werden.\n\nsubX: Eine Leistung besser als X, normalerweise wird dies verwendet, um eine einzelne Zeit (in Sekunden) oder eine einzelne Anzahl von Schritten zu beschreiben. Zum Beispiel bedeutet sub3, dass die Leistung innerhalb von 3 Sekunden erbracht wurde.',
  S.SharingandLearningDetail:
      'Wenn man ein Level nicht schafft, kann man in der "Beginners Group" einen Beitrag verfassen und um Hilfe bitten.',
  S.SharingandLearningDetail2:
      'Wenn man mehr über die Grundlagen von Klotski erfahren möchte, kann man sich in der "Science Group" austauschen und lernen.',
  S.SharingandLearningDetail3:
      'Wenn man Lösungen für klassische Klotski erfahren möchte, kann man sich in der "Classic Group" austauschen und lernen.',
  S.RulesDetailNum:
      'Bewegen Sie die Blöcke, um sie in aufsteigender Reihenfolge von links nach rechts und von oben nach unten zu sortieren.',
  S.HowtoPlayDetailNum:
      'Halten Sie den zu bewegenden Block gedrückt und schieben Sie ihn in beliebige Richtung. Die Zeit beginnt zu laufen, sobald Sie mit dem Schieben beginnen. Wenn Sie ein Gerät verwenden, müssen Sie es zuerst verbinden und gemäß den Geräteanweisungen das Spielbrett richtig platzieren. Drücken Sie dann die Bestätigungstaste, um das Schieben zu starten und die Zeit zu starten.',
  S.ModesDetailNum:
      '3 x 3 Stufen: Die Nummernblöcke können nur innerhalb eines 3x3-Bereichs verschoben werden. Sortieren Sie die Zahlenblöcke 1-8 in aufsteigender Reihenfolge von links nach rechts und von oben nach unten. Je nach Abschlusszeit erhalten Sie 1-3 Sterne.\n\n4 x 4 Stufen: Die Nummernblöcke können nur innerhalb eines 4x4-Bereichs verschoben werden. Sortieren Sie die Zahlenblöcke 1-15 in aufsteigender Reihenfolge von links nach rechts und von oben nach unten. Je nach Abschlusszeit erhalten Sie 1-3 Sterne.\n\nÜbungen: Der Spieler kann den Schwierigkeitsgrad von 3x3 oder 4x4 wählen. Das System generiert automatisch ein entsprechendes Spielfeld. Wenn Sie während des Trainings Schwierigkeiten haben, können Sie auf den intelligenten Lernmodus klicken, um vom KI-Assistenten unterstützt zu werden.\n\n1 GEGEN 1: Der Spieler kann den Schwierigkeitsgrad von 3x3 oder 4x4 wählen und entweder automatisch einen Gegner finden oder Freunde zum Duell einladen. Wenn Sie die automatische Zuordnung wählen, wird das System basierend auf den Gerätebedingungen automatisch einen Spieler mit dem gleichen Schwierigkeitsgrad für Sie auswählen. Wenn Sie Freunde einladen möchten, können Sie In-Game-Freunde zum Duell einladen, ohne auf Gerätebeschränkungen zu achten.',
  S.ResultsDetailNum:
      'Zeit: Die Zeit, die zum Abschließen des Spiels benötigt wird.\nSchritte: Jede Bewegung eines Blocks wird als ein Schritt gezählt.',
  S.CommonTerminologyDetailNum:
      '8p/15p/24p...: Bezieht sich auf drei Stufen / vier Stufen / fünf Stufen... des Zahlenrätsels.\n\ntps: Schritte pro Sekunde, d.h. die Anzahl der Schritte pro Sekunde. Zum Beispiel tps1.20 bedeutet, dass jede Sekunde 1,2 Schritte gemacht werden.\n\nsubX: Ergebnis unter X. Normalerweise bezieht es sich auf eine einzelne Zeitspanne (in Sekunden) oder eine einzelne Anzahl von Schritten. Zum Beispiel sub3 bedeutet ein Ergebnis von unter 3 Sekunden.',
  S.SharingandLearningDetailNum:
      'Wenn Sie Schwierigkeiten haben, eine Stufe abzuschließen, können Sie ins "Number Puzzle Group" gehen und einen Beitrag veröffentlichen, um Hilfe zu erhalten.',
  S.HrdTeachTitle: 'Anfängerleitfaden für Klotski',
  S.NumTeachTitle: 'Anfängerleitfaden für das Zahlenrätsel',
  S.ContactUs: 'Kontaktieren Sie uns',
  S.ContactUsDetail:
      'Wenn Sie Probleme bei der Verwendung der App haben, können Sie Ihr Feedback in der Gruppe veröffentlichen oder den QR-Code scannen, um "方块仔" hinzuzufügen, um Feedback zu geben',
  S.LookTeach: 'Anleitung anzeigen',
  S.Time: 'Zeit',
  S.Numberofvictories: 'Anzahl der Siege diese Woche',
  S.Winrate: 'Gewinnrate',
  S.Smartdeviceplayer: 'Spieler von intelligenten Geräten',
  S.Ready: 'Schon bereit',
  S.Prepare: 'Bereit machen',
  S.Thedevicehasbeendisconnected: 'Verbindung verloren',
  S.ProceedtoConnect: 'Zur Verbindung',
  S.Settings: 'Einstellungen',
  S.ConnectKlotski: 'Klotski verbinden',
  S.DeviceConnected: 'Verbunden',
  S.VSSettings: '1 GEGEN 1 Einstellungen',
  S.MatchSmartdeviceplayer: 'Passend Spieler von intelligenten Geräten',
  S.Waitingforfriendtoready: 'Warten auf den Bereit eines Freundes',
  S.Follow: 'Folgen',
  S.Applied: 'Angewandt',
  S.Thenumberofslidespersecond:
      'Züge pro Sekunde sind ein wichtiger Parameter zur Messung der Reaktionsgeschwindigkeit beim Spiel „Klotski“',
  S.Unknownlocation: 'Unbekannter Ort',
  S.Solutiondiscussion: 'Lösungsdiskussion',
  S.Goto: 'Hinzugehen',
  S.FamousGameSlogan: 'In die Drei Königreiche abenteuern, die Rangliste anführen',
  S.FreeGameSlogan: 'Fleißiger üben, blitzschneller sein',
  S.LevelGameSlogan: 'Mehr Levels erreichen, Sterne sammeln',
  S.LevelNumGameSlogan: 'Level erreichen, Sterne sammeln',
  S.RankGameSlogan: 'Freunde einladen, zusammen spielen',
  S.Checkthetutorialguideassistance: 'Überprüfen Sie den Anleitungsleitfaden für Hilfe',
  S.ThesolutionapproachforDifficultyN:
      'Der Lösungsansatz für "Schwierigkeitsgrad %s" wurde freigeschaltet. Möchtest du es dir ansehen?'
};
