import 'intl_keys.dart';

const es_ES_res = {
  S.OK: 'DE ACUERDO',
  S.Next: 'Próximo',
  S.Cancel: 'Cancelar',
  S.Connect: 'Conectar',
  S.Dis: 'Desconectar',
  S.Disconnect: 'Desconectar',
  S.Devicenotconnected: 'Dispositivo no conectado',
  S.Klotski: 'Klotski',
  S.NumberPuzzle: 'Rompecabezas numérico',
  S.Classic: 'Clásico',
  S.Practice: 'Practicar',
  S.Stages: 'Etapas',
  S.VS: '1 CONTRA 1',
  S.Devices: 'Dispositivos',
  S.Search: 'Buscar',
  S.Searching: 'Minucioso',
  S.Searchagain: 'Buscar de nuevo',
  S.Battery: 'Batería',
  S.Switch: 'Interruptor',
  S.FirmwareVersion: 'Versión del firmware',
  S.Bluetoothnotenabled: 'Bluetooth no habilitado',
  S.Enablebluetooth: 'Habilitar bluetooth',
  S.Renamedevice: 'Cambiar el nombre del dispositivo',
  S.Disconnectdevice: 'Desconectar dispositivo',
  S.FirmwareUpgrade: 'Actualización del firmware',
  S.Upgradefirmwareto: 'Actualice el firmware a',
  S.FirmwareupgradingPleasedonotclosetheapp: 'Actualización del firmware. Por favor, no cierre la aplicación',
  S.Customize: 'Personalizar',
  S.SlideTime: 'Diapositiva y tiempo',
  S.AITutorial: 'Tutorial de IA',
  S.StageSync: 'Sincronización de escenarios',
  S.syncappdevicestageprogress:
      'El progreso de la etapa de su dispositivo inteligente no es el mismo que el de la aplicación. ¿Quieres sincronizarlos?',
  S.Sync: 'Sincronizar',
  S.Records: 'Archivo',
  S.Invite: 'Invitar',
  S.Move: 'Movimientos',
  S.PreviousStep: 'Paso anterior',
  S.Speed: ' x',
  S.Puttingoneselfinsomeoneelsesshoes: 'Ponerse en el lugar de otra persona',
  S.ThreeHeroesSwearBrotherhoodInThePeachGarden: 'Los Tres Héroes Jurando Hermandad en el Jardín de los Melocotones',
  S.FuXisEightTrigramsWaterKanTrigram: 'Los Ocho Trigramas de Fu Xi: Trigrama del Agua Kan',
  S.PassFiveLevels: 'Pasa cinco niveles',
  S.Domineeringandtyrannical: 'Dominante y tiránico',
  S.TheThreeBrothersFightAgainstLuBu: 'Los Tres Hermanos Luchan contra Lu Bu',
  S.Drawingaswordandmountingahorse: 'Sacando una espada y montando a caballo',
  S.LiuBeiPaysThreeVisitsToZhugeLiangscottage: 'Liu Bei hace tres visitas a la cabaña de Zhuge Liang',
  S.Settingfiretotheconnectedcamps: 'Incendiando los campamentos conectados',
  S.Devicenamemodifiedsuccessfully: 'Completado',
  S.Failed: 'Fracasado',
  S.FirmwareUpdateSuccessfully: 'Actualización correcta del firmware',
  S.Back: 'Atrás',
  S.Newrecord: 'Nuevo récord',
  S.Noscore: 'Sin puntuación',
  S.PleaseselecttheStageyouwanttosync: 'Seleccione el escenario que desea sincronizar',
  S.GANKlotski: 'GAN Klotski',
  S.Inprogress: 'En curso',
  S.SyncCompleted: 'Completado',
  S.automatching: 'Coincidencia automática',
  S.Recommendedstage: 'Etapa recomendada',
  S.selectachessgame: 'Seleccione una partida de ajedrez',
  S.quit: 'Renunciar',
  S.Completed: 'Completado',
  S.pressOKafterplacingthepieces: "Presione 'OK' después de colocar las piezas",
  S.recordofClassic: 'Grabación de Clásico',
  S.Chessgame: 'Juego de ajedrez',
  S.moves: 'Movimientos',
  S.Score: 'Puntuación',
  S.Selectstage: 'Seleccionar etapa',
  S.Advancedstage: 'Etapa avanzada',
  S.ultimatechallenge: 'El desafío definitivo',
  S.Challengefailed: 'Fracasado',
  S.Placementisabnormalpleaserearrange: 'La colocación es anormal, por favor reorganice',
  S.Giveupchallenge: 'Renunciar',
  S.shareGame: 'Compartir',
  S.Customchessgame: 'Juego de ajedrez personalizado',
  S.reset: 'Restablecimiento',
  S.Thischessgamehasnosolutionpleaserearrangethepieces:
      'Este juego de ajedrez no tiene solución, por favor reorganice las piezas',
  S.Thischessgameiscompletedpleaserearrange: 'Este juego de ajedrez se ha completado, por favor reorganice',
  S.Practicerecord: 'Registro de práctica',
  S.infinitestages: 'Etapas infinitas',
  S.Win: 'Ganar',
  S.next: 'Próximo',
  S.youcantgetstarswithAItutorialcontinue: 'No puedes obtener estrellas con el tutorial de IA, ¿continúas?',
  S.remaining: 'Restante',
  S.Tutorialcompleted: 'Tutorial completado',
  S.restart: 'Reanudar',
  S.stagerecords: 'Récords escénicos',
  S.Invitation: 'Invitación de un amigo',
  S.stageprogress: 'Estado de la etapa',
  S.Inviting: 'Tentador',
  S.hasdeclined: ' ha disminuido',
  S.Start: 'Empezar',
  S.Waitingforfriendtostart: 'Esperando a que un amigo comience',
  S.Gamehasntstartedleavetheroom: 'El juego no ha comenzado, ¿salir de la habitación?',
  S.Matching: 'Cotejo...',
  S.Esimatedtime: 'Tiempo esimado ',
  S.seconds: ' s',
  S.matchfound: 'Coincidencia encontrada',
  S.startingthegame: 'Inicio del juego',
  S.hasquitrematch: 'Rival ha renunciado, ¿revancha?',
  S.hasquit: 'Rival ha renunciado',
  S.Rematch: 'Revancha',
  S.placement: 'Colocación',
  S.observation: 'Observación',
  S.Placing: 'Colocación',
  S.Observing: 'Observando',
  S.solving: 'Jugando',
  S.waitfortocompletethegame: 'Espera a Rival para completar el juego',
  S.time: 'Hora',
  S.solvemoves: 'Movimientos',
  S.Playagain: 'Juega de nuevo',
  S.timeout: 'Interrupción',
  S.failurewithoutfinishStillquit:
      'Se considerará un fracaso si abandonas sin terminar el juego. ¿Aún dejaste de fumar?',
  S.Reconnecting: 'Reconectar',
  S.vsrecords: 'Historia de 1 vs.1',
  S.Winloss: 'Victorias/derrotas',
  S.stage3x3: '3 x 3 etapas',
  S.stage4x4: '4 x 4 etapas',
  S.minsago: ' m ago',
  S.hrsago: ' hrs ago',
  S.Stage: 'Etapa de dificultad',
  S.dengji: 'Etapa',
  S.replayplayback: 'Reproducir otra vez',
  S.Norecords: 'Sin registros',
  S.Nofriends: 'Todavía no hay amigos',
  S.Play: 'Ir a jugar',
  S.Forbeginners: 'Para principiantes',
  S.Joindiscussion: 'Juntar',
  S.closeTutorial: 'Cerrar',
  S.DeviceInformation: 'Información del dispostivo',
  S.DeviceType: 'Tipo de dispositivo',
  S.Model: 'Modelo de dispositivo',
  S.update: 'Actualización',
  S.infinite: 'infinitas',
  S.Lv: 'Etapa %s',
  S.stageprogresoverwrittenunlockedlevel:
      'El progreso de la etapa %s se sobrescribirá después de la sincronización Se desbloqueará al nivel %s',
  S.PlaywithGANKlotski: 'Juega con GAN Klotski',
  S.PlaywithoutGANKlotski: 'Juega sin GAN Klotski',
  S.gamedonotfinish: 'El juego no termina',
  S.Connecting: 'Conectivo',
  S.Donotfinished: 'No terminado',
  S.Offline: 'Sin conexión',
  S.Countdown: 'Cuenta regresiva',
  S.Waiting: 'En espera',
  S.Locked: 'Cerrado con llave',
  S.connectsmartdeviceunlockVS:
      'Conecte primero el dispositivo inteligente "Klotski" para desbloquear la función 1 VS 1.',
  S.chessCompleted: 'Completado',
  S.knowresultstillquite: 'Sabrás el resultado una vez que el oponente haya terminado, ¿todavía bastante?',
  S.Networkissuepleaseretrylater: 'Problema de red, vuelva a intentarlo más tarde',
  S.Failedcompletegameinspecifiedtime: 'No se pudo restaurar el juego de ajedrez en el plazo de tiempo especificado',
  S.interruptinvitation: 'Cerrar la interfaz interrumpirá la invitación, ¿continuar?',
  S.friendInviting: 'Invitación',
  S.resolving: 'resolver',
  S.placethepiecesfirst: 'Coloca las piezas primero',
  S.Networkissue: 'Problema de red',
  S.Refresh: 'Actualizar',
  S.Doubleclickchesstoremove: 'Doble clic en una pieza de ajedrez dentro del tablero para eliminarla',
  S.Connected: 'Conexo',
  S.Devicenotfound: 'Dispositivo no encontrado',
  S.Quitgame: 'Renunciar',
  S.Random: 'Aleatorio',
  S.ShareScore: 'Compartir',
  S.StageCompleted: 'Completado',
  S.Gamedonotfinishstillquite: 'El juego no termina, ¿Aún dejaste de fumar?',
  S.WaitUnLocked: 'Cerrado con llave',
  S.Downloading: 'Descargar',
  S.Downloaded: 'Descargó',
  S.gamenotoverregeneratenewgame: 'Aún no terminó la partida. ¿Desea volver a generar una partida nueva?',
  S.Selectdate: 'Seleccionar fecha',
  S.Pleaseoperatesmartdevice: 'Úselo con un dispositivo pequeño.',
  S.Reachedmaximumlevel: 'Se alcanzó el nivel máximo.',
  S.disconnectotherdevicesfirst: 'Primero, desconecte otros dispositivos.',
  S.UpdateruleseveryMondayupdatedata:
      'Los datos de la clasificación semanal se calculan desde las 08:00:00 del lunes hasta las 07:59:59 del lunes siguiente en tiempo universal coordinado. Las puntuaciones de la clasificación de la semana anterior se liquidan a las 08:00:00 todos los lunes. \n\nLas reglas de clasificación para la clasificación son las siguientes:\n1. La clasificación se basa en el tiempo de finalización, siendo los tiempos más cortos los que obtienen una clasificación más alta.\n2. En casos en los que los tiempos de finalización son iguales, la clasificación se basa en el número de pasos realizados, siendo menos pasos los que obtienen una clasificación más alta.\n3. Si tanto los tiempos de finalización como el número de pasos son iguales, la clasificación se basa en el momento en que se ingresaron en la clasificación, siendo los momentos anteriores los que obtienen una clasificación más alta.',
  S.UpdateruleseveryMondayupdatedataCHN:
      'Los datos de clasificación semanal se calculan desde el lunes 00:00:00 hasta el domingo 23:59:59 hora de Pekín. Cada lunes a las 00:00:00 se calculan los resultados de la clasificación de la semana anterior. \n\nLas reglas de clasificación son las siguientes:\n1. La clasificación se basa en el tiempo de finalización, siendo los tiempos más cortos los que obtienen una clasificación más alta.\n2. En casos en los que los tiempos de finalización son iguales, la clasificación se basa en el número de pasos realizados, siendo menos pasos los que obtienen una clasificación más alta.\n3. Si tanto los tiempos de finalización como el número de pasos son iguales, la clasificación se basa en el momento en que se ingresaron en la clasificación, siendo los momentos anteriores los que obtienen una clasificación más alta.',
  S.CST: 'CST',
  S.EDT: 'EDT',
  S.Notonlist: 'No está en la lista',
  S.Thisweek: 'Esta semana',
  S.rankinglist: 'Lista de clasificación',
  S.UnderAITeachingnotgetscore: 'Si opta por la Enseñanza con IA, no recibirá una puntuación. ¿Desea continuar?',
  S.timesisuseduptoday: 'Hoy ya se alcanzó el número de veces permitido',
  S.Youhavenchanceslefttoday: 'Tienes %s oportunidades restantes hoy',
  S.ChallengeSettlement: 'Desafío a la liquidación',
  S.BrandName: 'Nombre de marca',
  S.DeviceModel: 'Modelo de dispositivo',
  S.BluetoothAddress: 'Dirección Bluetooth',
  S.ProductName: 'Nombre del producto',
  S.Username: 'Nombre de usuario',
  S.UploadingPleaseWait: 'Subiendo, por favor espera',
  S.StartChallenge: 'Empezar',
  S.Timehasrunout: 'Se ha acabado el tiempo',
  S.Outofmoves: 'Sin más movimientos',
  S.OnlyNstepsawayfromsolving: 'Es una lástima, a solo %s pasos de resolver el juego de ajedrez',
  S.Congratulationsonsolvingthechessgame:
      'Felicitaciones por resolver el juego de ajedrez. Ven y prueba a desafiarte a ti mismo.',
  S.Basicinstructions: 'Instrucciones básicas',
  S.Solutionapproach: 'Enfoque de solución',
  S.Rules: 'Reglas',
  S.HowtoPlay: 'Método de operación',
  S.Modes: 'Modos de juego',
  S.Results: 'Resultados',
  S.CommonTerminology: 'Términos comunes',
  S.SharingandLearning: 'Compartir y aprender',
  S.RulesDetail:
      'Mueva las diferentes piezas para ayudar al bloque grande a moverse desde su posición inicial hasta el centro inferior del tablero, sin saltar por encima de las piezas. El éxito en "escapar" significa que ha pasado la etapa.',
  S.HowtoPlayDetail:
      'Mantenga presionado el bloque que desea mover y deslícelo en cualquier dirección. El tiempo comienza a contar desde el inicio del deslizamiento. Para los jugadores con dispositivos, deben conectar primero el dispositivo y colocar correctamente el ajedrez según las indicaciones antes de confirmar y deslizar.',
  S.ModesDetail:
      'Clásico: Este modo se actualizará periódicamente con nuevos niveles. Se liberarán 9 niveles cada vez que se actualice, lo que cubrirá los niveles originales anteriores. Los jugadores pueden ver las puntuaciones anteriores del nivel original mediante el cambio del tiempo en la lista.\n\nEtapas: Los jugadores pueden pasar las etapas en orden y obtener 1-3 estrellas según el tiempo que les lleve completar cada nivel.\n\nPracticar: Los jugadores pueden elegir entre 1 y 13 niveles de dificultad, y el sistema generará automáticamente el ajedrez correspondiente. Si tienen problemas durante el proceso de práctica, pueden hacer clic en "Enseñanza inteligente" para seguir aprendiendo con IA.\n\n1 CONTRA 1: Los jugadores pueden elegir entre 1 y 13 niveles de dificultad, y seleccionar la opción de emparejamiento automático o invitar a amigos para luchar. Si eligen emparejamiento automático, el sistema seleccionará automáticamente jugadores de la misma dificultad según las condiciones del dispositivo. Si eligen invitar a amigos, pueden luchar con amigos dentro de la plataforma sin restricciones de conexión de dispositivos.',
  S.ResultsDetail:
      'Tiempo: El tiempo que se tarda en completar el juego.\nPasos: Cada movimiento de una pieza se cuenta como un paso.',
  S.CommonTerminologyDetail:
      'tps: La cantidad de movimientos por segundo, es decir, los pasos divididos por el tiempo en segundos. Por ejemplo, tps1.20 indica que se mueven 1,2 pasos por segundo.\n\nsubX: Un resultado "sub X" significa que está por debajo de X. Por lo general, se refiere al tiempo o la cantidad de pasos necesarios para completar un nivel. Por ejemplo, sub3 significa que la puntuación es inferior a 3 segundos.',
  S.SharingandLearningDetail:
      'Si no puede pasar un nivel, puede publicar una publicación en el grupo "Beginners Group" para pedir ayuda.',
  S.SharingandLearningDetail2:
      'Si desea obtener más información sobre el ajedrez de Klotski, puede acudir al grupo "Science Group" para intercambiar y aprender.',
  S.SharingandLearningDetail3:
      'Si desea conocer las soluciones para los niveles clásicos de Klotski, puede acudir al grupo "Classic Group" para intercambiar y aprender.',
  S.RulesDetailNum: 'Mueve los cuadrados para ordenarlos de izquierda a derecha, de arriba abajo y por orden numérico.',
  S.HowtoPlayDetailNum:
      'Mantén presionado el cuadrado que deseas mover y deslízalo en cualquier dirección. El tiempo comienza a contar cuando comienzas a deslizarlo. Los jugadores con dispositivos necesitan conectarse primero y seguir las indicaciones del dispositivo para colocar el tablero correctamente. Luego, al presionar el botón de confirmación, el tiempo comienza a contar.',
  S.ModesDetailNum:
      '3 x 3 etapas: Los cuadrados numéricos deben moverse dentro de un área de 3x3. Ordena los números del 1 al 8 de izquierda a derecha, de arriba abajo y por orden numérico. Dependiendo del tiempo necesario para completar el desafío, se pueden obtener de 1 a 3 estrellas.\n\n4 x 4 etapas: Los cuadrados numéricos deben moverse dentro de un área de 4x4. Ordena los números del 1 al 15 de izquierda a derecha, de arriba abajo y por orden numérico. Dependiendo del tiempo necesario para completar el desafío, se pueden obtener de 1 a 3 estrellas.\n\nPracticar: Los jugadores pueden elegir la dificultad de 3x3 o 4x4 y el sistema generará automáticamente el tablero correspondiente. Si encuentras dificultades durante la práctica, puedes hacer clic en el aprendizaje inteligente para seguir a AI para aprender.\n\nPracticar: Los jugadores pueden elegir la dificultad de 3x3 o 4x4 y el sistema generará automáticamente el tablero correspondiente. Si encuentras dificultades durante la práctica, puedes hacer clic en el aprendizaje inteligente para seguir a AI para aprender.\n\n1 CONTRA 1: Los jugadores pueden elegir la dificultad de 3x3 o 4x4 y pueden optar por una partida automática o invitar a amigos a jugar. Si eliges una partida automática, el sistema buscará jugadores con dificultades similares para que jueguen juntos. Si eliges invitar a un amigo, puedes jugar juntos sin restricciones de conexión.',
  S.ResultsDetailNum:
      'Tiempo: El tiempo necesario para completar el juego.\nPasos: Cada movimiento de un cuadrado se cuenta como un paso.',
  S.CommonTerminologyDetailNum:
      '8p/15p/24p...: Se refiere a los desafíos de 3x3/4x4/5x5... números.\n\ntps: Número de pasos por segundo, es decir, el número de pasos dividido por el tiempo en segundos. Por ejemplo, tps1.20 significa que se mueve 1,2 pasos por segundo.\n\nsubX: Los resultados son inferiores a X, generalmente se refiere al tiempo o a la cantidad de pasos necesarios para un solo intento. Por ejemplo, sub3 significa un resultado inferior a 3 segundos.',
  S.SharingandLearningDetailNum:
      'Si tienes problemas para pasar un nivel, puedes publicar una consulta en el grupo Number Puzzle Group.',
  S.HrdTeachTitle: 'Guía para principiantes de Klotski',
  S.NumTeachTitle: 'Guía para principiantes del Rompecabezas Numérico',
  S.ContactUs: 'Contáctenos',
  S.ContactUsDetail:
      'Si encuentra algún problema al utilizar la aplicación, puede publicar sus comentarios en el grupo o escanear el código QR para agregar "方块仔" para recibir comentarios',
  S.LookTeach: 'Ver instrucciones',
  S.Time: 'Tiempo',
  S.Numberofvictories: 'Victorias Ganadas esta semana',
  S.Winrate: 'Tasa de victorias',
  S.Smartdeviceplayer: 'Jugador de dispositivos inteligentes',
  S.Prepare: 'Prepararse',
  S.Ready: 'Listo',
  S.Thedevicehasbeendisconnected: 'El dispositivo se ha desconectado',
  S.ProceedtoConnect: 'Ir a la conexión',
  S.Settings: 'Configuración',
  S.ConnectKlotski: 'Conectar Klotski',
  S.DeviceConnected: 'Conexo',
  S.VSSettings: '1 CONTRA 1 Configuración',
  S.MatchSmartdeviceplayer: 'Coincidencia Jugador de dispositivos inteligentes',
  S.Waitingforfriendtoready: 'Esperando a que un amigo Listo',
  S.Follow: 'Seguir',
  S.Applied: 'Aplicado',
  S.Thenumberofslidespersecond:
      'El número de deslices por segundo es un parametro importante para medir la velocidad de la mano de Klotski',
  S.Unknownlocation: 'Ubicación desconocida',
  S.Solutiondiscussion: 'Discusión de la solución',
  S.Goto: 'Ir a',
  S.FamousGameSlogan: 'Aventurarse en los tres reinos y competir en la lista',
  S.FreeGameSlogan: 'Entrena constantemente para hacer estallar tu velocidad',
  S.LevelGameSlogan: 'Supera 1000 niveles y colecciona estrellas',
  S.LevelNumGameSlogan: 'Supera los niveles para coleccionar estrellas',
  S.RankGameSlogan: 'Invitar amigos para jugar juntos',
  S.Checkthetutorialguideassistance: 'Consulta la guía de tutorial para obtener ayuda',
  S.ThesolutionapproachforDifficultyN:
      'El enfoque de solución para "Dificultad %s" ha sido desbloqueado. ¿Te gustaría ir a verlo?s'
};
