import 'intl_keys.dart';

const ja_JP_res = {
  S.OK: 'わかりました',
  S.Next: '次に',
  S.Cancel: 'キャンセル',
  S.Connect: '繋ぐ',
  S.Dis: '切る',
  S.Disconnect: '切る',
  S.Devicenotconnected: 'デバイスが接続されていません',
  S.Klotski: 'クロツキー',
  S.NumberPuzzle: 'デジタルクロツキー',
  S.Classic: 'クラシック',
  S.Practice: '練習',
  S.Stages: '段階',
  S.VS: '1対1',
  S.Devices: 'デバイス',
  S.Search: '捜索',
  S.Searching: '探訪',
  S.Searchagain: '再検索',
  S.Battery: '電池',
  S.Switch: 'スイッチ',
  S.FirmwareVersion: 'ファームウェアバージョン',
  S.Bluetoothnotenabled: 'Bluetoothが有効になっていません',
  S.Enablebluetooth: 'ブルートゥースを有効にする',
  S.Renamedevice: 'デバイス名の変更',
  S.Disconnectdevice: 'デバイスの切断',
  S.FirmwareUpgrade: 'ファームウェアのアップグレード',
  S.Upgradefirmwareto: 'ファームウェアをにアップグレードします',
  S.FirmwareupgradingPleasedonotclosetheapp: 'ファームウェアのアップグレード アプリを閉じないでください',
  S.Customize: 'カスタマイズ',
  S.SlideTime: 'スライド&タイム',
  S.AITutorial: 'AIチュートリアル',
  S.StageSync: 'ステージ同期',
  S.syncappdevicestageprogress: 'スマートデバイスのステージの進行状況は、アプリと同じではありません。それらを同期しますか?',
  S.Sync: '同期',
  S.Records: '誌',
  S.Invite: '招く',
  S.Move: '移動',
  S.PreviousStep: '前のステップ',
  S.Speed: '倍',
  S.Puttingoneselfinsomeoneelsesshoes: '他人の立場に立つ',
  S.ThreeHeroesSwearBrotherhoodInThePeachGarden: '三英傑、桃園で兄弟の誓いを立てる',
  S.FuXisEightTrigramsWaterKanTrigram: '伏羲の八卦：水の坎卦',
  S.PassFiveLevels: '5つのレベルに合格',
  S.Domineeringandtyrannical: '横暴で専制的',
  S.TheThreeBrothersFightAgainstLuBu: '三兄弟、呂布に立ち向かう',
  S.Drawingaswordandmountingahorse: '刀を抜いて馬に乗る',
  S.LiuBeiPaysThreeVisitsToZhugeLiangscottage: '劉備、諸葛亮の小屋に三度訪れる',
  S.Settingfiretotheconnectedcamps: 'つながったキャンプに火をつける',
  S.Devicenamemodifiedsuccessfully: '完了',
  S.Failed: '失敗しました',
  S.FirmwareUpdateSuccessfully: 'ファームウェアが正常に更新されました',
  S.Back: '戻る',
  S.Newrecord: '新記録',
  S.Noscore: 'スコアなし',
  S.PleaseselecttheStageyouwanttosync: '同期したいステージを選択してください',
  S.GANKlotski: 'ガン・クロツキー',
  S.Inprogress: '進行中で',
  S.SyncCompleted: '完了',
  S.automatching: 'オートマッチング',
  S.Recommendedstage: '推奨ステージ',
  S.selectachessgame: 'チェスゲームの選択',
  S.quit: '辞める',
  S.Completed: '完了',
  S.pressOKafterplacingthepieces: 'ピースを配置した後、「OK」を押します',
  S.recordofClassic: 'クラシックの記録',
  S.Chessgame: 'チェスゲーム',
  S.moves: '移動',
  S.Score: 'スコア',
  S.Selectstage: 'ステージを選択',
  S.Advancedstage: 'アドバンスステージ',
  S.ultimatechallenge: '究極の挑戦',
  S.Challengefailed: '失敗しました',
  S.Placementisabnormalpleaserearrange: '配置が異常です。並べ替えてください',
  S.Giveupchallenge: '辞める',
  S.shareGame: '共有',
  S.Customchessgame: 'カスタムチェスゲーム',
  S.reset: 'リセット',
  S.Thischessgamehasnosolutionpleaserearrangethepieces: 'このチェスゲームには解決策がありません、駒を再配置してください',
  S.Thischessgameiscompletedpleaserearrange: 'このチェスゲームは完成しました、再配置してください',
  S.Practicerecord: '練習記録',
  S.infinitestages: '無限のステージ',
  S.Win: '勝つ',
  S.next: '次に',
  S.youcantgetstarswithAItutorialcontinue: 'AIチュートリアルで星を獲得することはできません、続行しますか?',
  S.remaining: '残り',
  S.Tutorialcompleted: 'チュートリアルが完了しました',
  S.restart: '再起動',
  S.stagerecords: 'ステージ記録',
  S.Invitation: '友人を招待する',
  S.stageprogress: 'ステージステータス',
  S.Inviting: '招待',
  S.hasdeclined: 'は辞退しました',
  S.Start: '始める',
  S.Waitingforfriendtostart: 'フレンドの開始を待っています',
  S.Gamehasntstartedleavetheroom: 'ゲームが始まっていません、退出しますか?',
  S.Matching: 'マッチング...',
  S.Esimatedtime: 'シミュレートされた時間',
  S.seconds: 's',
  S.matchfound: '一致が見つかりました',
  S.startingthegame: 'ゲームの開始',
  S.hasquitrematch: 'xxxは終了しました、リマッチしますか?',
  S.hasquit: '相手は終了しました、',
  S.Rematch: '再戦',
  S.placement: '位置付け',
  S.observation: '観察',
  S.Placing: '配置',
  S.Observing: '遵奉',
  S.solving: '演奏',
  S.waitfortocompletethegame: '相手がゲームを完了するのを待ちます',
  S.time: '時間',
  S.solvemoves: '移動',
  S.Playagain: 'もう一度プレイする',
  S.timeout: 'タイムアウト',
  S.failurewithoutfinishStillquit: 'ゲームを終了せずに終了した場合は失敗と見なされます。まだやめますか?',
  S.Reconnecting: '再接続',
  S.vsrecords: '1対1の履歴',
  S.Winloss: '勝敗',
  S.stage3x3: '3 x 3ステージ',
  S.stage4x4: '4 x 4ステージ',
  S.minsago: ' m 前',
  S.hrsago: ' 時間前',
  S.Stage: '難易度',
  S.dengji: 'ステージ',
  S.replayplayback: 'リプレイする',
  S.Norecords: 'レコードなし',
  S.Nofriends: 'まだ友達はいません',
  S.Play: 'プレイする',
  S.Forbeginners: '初心者向け',
  S.Joindiscussion: '接続',
  S.closeTutorial: '閉める',
  S.DeviceInformation: 'デバイス情報',
  S.DeviceType: 'デバイスタイプ',
  S.Model: 'デバイスモデル',
  S.update: '更新',
  S.infinite: '無限',
  S.Lv: 'ステージ %s',
  S.stageprogresoverwrittenunlockedlevel: '同步后%s闯关进度将被覆盖，解锁至第%s关 同期後%sステージの進行状況が上書きされます レベル%sのロックが解除されます',
  S.PlaywithGANKlotski: 'ガン・クロツキーと遊ぶ',
  S.PlaywithoutGANKlotski: 'ガン・クロツキーなしでプレイ',
  S.gamedonotfinish: 'ゲームが終了しない',
  S.Connecting: '接続',
  S.Donotfinished: '終了しない',
  S.Offline: 'オフライン',
  S.Countdown: 'カウントダウン',
  S.Waiting: '待機中',
  S.Locked: '締まる',
  S.connectsmartdeviceunlockVS: '最初に「Klotski」スマートデバイスを接続して、1VS1機能のロックを解除してください。',
  S.chessCompleted: '完了',
  S.knowresultstillquite: '相手完成で結果を知ることになります。それでも?',
  S.Networkissuepleaseretrylater: 'ネットワークの問題。後で再試行してください',
  S.Failedcompletegameinspecifiedtime: '定められた時間内にチェスの対局を再開できませんでした',
  S.interruptinvitation: 'インターフェイスを閉じると招待が中断されます、続行しますか?',
  S.friendInviting: '招待',
  S.resolving: '解決',
  S.placethepiecesfirst: 'ピースを最初に置きます',
  S.Networkissue: 'ネットワークの問題',
  S.Refresh: 'リフレッシュ',
  S.Doubleclickchesstoremove: 'チェスボード内の駒をダブルクリックして削除します',
  S.Connected: '接続',
  S.Devicenotfound: 'デバイスが見つかりません',
  S.Quitgame: '辞める',
  S.Random: 'ランダム',
  S.ShareScore: '共有',
  S.StageCompleted: '完了',
  S.Gamedonotfinishstillquite: 'ゲームが終了しない まだやめますか?',
  S.WaitUnLocked: '締まる',
  S.Downloading: 'ダウンロード',
  S.Downloaded: 'ダウンロード',
  S.gamenotoverregeneratenewgame: 'ゲームはまだ終わっていません。新しいゲームを再生成しますか？',
  S.Selectdate: '日付を選択してください',
  S.Pleaseoperatesmartdevice: 'スマートデバイスで操作してください',
  S.Reachedmaximumlevel: '最大レベルに到達しました',
  S.disconnectotherdevicesfirst: '最初に他のデバイスを切断してください',
  S.UpdateruleseveryMondayupdatedata:
      'ウィークリーリーダーボードデータは、UTC時間の月曜日08:00:00から翌週の月曜日07:59:59まで計算されます。前週のリーダーボードのスコアは、毎週月曜日の08:00:00に決済されます。\n\nリーダーボードのランキングルールは次のとおりです。\n1. クリアタイムに基づいてランキングが行われ、タイムが短いほどランキングが高くなります。\n2. クリアタイムが同じ場合、ステップ数に基づいてランキングが行われ、より少ないステップがより高いランキングをもたらします。\n3. クリアタイムとステップ数が同じ場合、リーダーボードへの掲載時間に基づいてランキングが行われ、より早い時間がより高いランキングをもたらします。',
  S.UpdateruleseveryMondayupdatedataCHN:
      '週間ランキングデータは、月曜日00:00:00から日曜日23:59:59の北京時間で計算されます。毎週月曜日の00:00:00に、前週のランキング結果が計算されます。\n\nランキングのルールは次のとおりです。\n1. クリアタイムに基づいてランキングが行われ、タイムが短いほどランキングが高くなります。\n2. クリアタイムが同じ場合、ステップ数に基づいてランキングが行われ、より少ないステップがより高いランキングをもたらします。\n3. クリアタイムとステップ数が同じ場合、リーダーボードへの掲載時間に基づいてランキングが行われ、より早い時間がより高いランキングをもたらします。',
  S.CST: 'CST',
  S.EDT: 'EDT',
  S.Notonlist: 'リストにありません',
  S.Thisweek: '今週',
  S.rankinglist: 'ランキングリスト',
  S.UnderAITeachingnotgetscore: 'AIティーチングではスコアを得ることはできません。続行してもよろしいですか？',
  S.timesisuseduptoday: '本日で限定回数が使い終わります',
  S.Youhavenchanceslefttoday: '本日 %s 回の機会が残っています',
  S.ChallengeSettlement: 'チャレンジ決済',
  S.BrandName: 'ブランド名',
  S.DeviceModel: 'デバイスモデル',
  S.BluetoothAddress: 'Bluetoothアドレス',
  S.ProductName: '製品名',
  S.Username: 'ユーザー名',
  S.UploadingPleaseWait: 'アップロード中、しばらくお待ちください',
  S.StartChallenge: '始める',
  S.Timehasrunout: '時間切れ',
  S.Outofmoves: '手が尽きました',
  S.OnlyNstepsawayfromsolving: '残念です、チェスゲームの解決まであと%s手',
  S.Congratulationsonsolvingthechessgame: 'チェスのゲームを解決したおめでとうございます。自分で挑戦してみてください。',
  S.Basicinstructions: '基本的な説明',
  S.Solutionapproach: '解決策のアプローチ',
  S.Rules: 'ルール',
  S.HowtoPlay: '操作方法',
  S.Modes: 'モード',
  S.Results: '結果',
  S.CommonTerminology: '一般的な用語の説明',
  S.SharingandLearning: '共有と学習',
  S.RulesDetail: '各ブロックを移動させ、大きなブロックを初期位置からボードの中央下部まで移動させること。移動中に他のブロックを飛び越えることはできず、"脱出"が成功すればクリアとなる。',
  S.HowtoPlayDetail:
      '移動したいブロックを押し続け、任意の方向にスライドさせる。スライド開始でタイマーがスタートする。機器を持っているプレーヤーは、まずデバイスを接続し、デバイスの指示に従って盤面を配置し、確定ボタンを押してスライドを開始するとタイマーがスタートする。',
  S.ModesDetail:
      'クラシック：このモードでは、定期的に新しいステージが追加され、毎回9つのステージがリリースされる。更新後は元の9つのステージが上書きされ、プレーヤーはリーダーボード時間を切り替えて元のステージのスコアを確認することができる。\n\n段階：プレーヤーは順番にステージに挑戦して進んでいくことができ、クリア時間に応じて1〜3つの星を獲得することができる。\n\n練習：プレーヤーは1〜13の難易度を選択し、システムは対応する難易度の盤面を自動生成する。練習中に困難が生じた場合は、AIのスマートティーチングをクリックしてAIに従って学習することができる。\n\n1対1：プレーヤーは1〜13の難易度を選択し、オートマッチまたは友達を招待して対戦することができる。オートマッチを選択した場合、システムはデバイスの状況に基づいて同じ難易度を選んだプレーヤーと対戦する。友達を招待した場合、サイト内の友達と対戦することができ、デバイスの接続制限はありません。',
  S.ResultsDetail: '時間：ゲームのクリアにかかった時間 \n手数：各ブロックの移動を1手としてカウントする',
  S.CommonTerminologyDetail:
      'tps：1秒あたりの移動手数で、手数を秒単位で割ったもの。例えばtps1.20は、1秒に1.2手の移動を意味する。\n\nsubX：成績がX以下であることを示し、通常は単一のタイムスコア（秒単位）または単一の手数スコア（手単位）を意味する。例えばsub3は、成績が3秒以内であることを示す。',
  S.SharingandLearningDetail: 'ステージをクリアできない場合は、「Beginners Group」に投稿して助けを求めることができます。',
  S.SharingandLearningDetail2: 'もっとクロツキーの局面について学びたい場合は、「Science Group」に参加して交流し学習することができます。',
  S.SharingandLearningDetail3: 'クロツキーのクラシックなステージの解法について知りたい場合は、「Classic Group」に参加して交流し学習することができます。',
  S.RulesDetailNum: 'ブロックを動かし、左から右に、上から下に、小さい順に並べます。',
  S.HowtoPlayDetailNum:
      'したいブロックを押し続け、任意の方向にスライドします。デバイスを持っているプレーヤーは、まずデバイスを接続し、デバイスの指示に従って配置を行った後、確認キーを押してスライドを開始すると計時が開始されます。',
  S.ModesDetailNum:
      '3 x 3ステージ：数字ブロックは3×3の領域内で動かされ、1-8の数値ブロックを左から右に、上から下に、小さい順に並べ替えます。クリア時間に応じて、1-3つの星を獲得します。\n\n4 x 4ステージ：数字ブロックは4×4の領域内で動かされ、1-15の数字ブロックを左から右に、上から下に、小さい順に並べ替えます。クリア時間に応じて、1-3つの星を獲得します。\n\n練習：プレーヤーは3×3、4×4の難易度を選び、システムが対応する難易度の局面を自動生成します。練習中に困難が生じた場合、AIのスマートティーチングに従って学習することもできます。\n\n1対1：プレーヤーは3×3、4×4の難易度を選び、自動マッチングまたは友達を招待して対戦できます。自動マッチングを選択した場合、システムはデバイスの状況に応じて、同等の難易度のプレーヤーを自動的にマッチングし、共に対戦します。友達を招待した場合、サイト内の友達を招待して、デバイス接続の制限を受けることなく一緒に対戦することができます。',
  S.ResultsDetailNum: '時間：ゲームをクリアするために使用された時間\n手数：ブロックを1つ移動するごとに1手としてカウントされます。',
  S.CommonTerminologyDetailNum:
      '8p/15p/24p......：それぞれ3 x 3/4 x 4/5 x 5......の数字パズルを指します。\n\ntps：秒当たりの移動数、つまり、秒単位での手数です。例えばtps1.20は、1.2手/秒を表します。\n\nsubX：X以下の成績、通常は単一のタイムスコア（単位：秒）または単一のステップスコア（単位：手）を説明するために使用されます。例えば、sub3は3秒以内の成績を表します。',
  S.SharingandLearningDetailNum: 'ステージをクリアできない場合は、「Number Puzzle Group」で投稿して助けを求めることができます。',
  S.HrdTeachTitle: '華容道初心者ガイド',
  S.NumTeachTitle: 'ナンバーパズル初心者ガイド',
  S.ContactUs: 'お問い合わせ',
  S.ContactUsDetail: 'アプリの使用中に問題が発生した場合は、グループにフィードバックを投稿するか、QRコードをスキャンして「方块仔」を追加してフィードバックを行うことができます',
  S.LookTeach: '教示を見る',
  S.Time: '時間',
  S.Numberofvictories: '今週の勝利数',
  S.Winrate: '勝率',
  S.Smartdeviceplayer: 'スマートデバイスプレイヤー',
  S.Ready: '準備中',
  S.Prepare: '準備',
  S.Thedevicehasbeendisconnected: '端末の接続が切れました',
  S.ProceedtoConnect: '接続する',
  S.Settings: '設定',
  S.ConnectKlotski: 'ガンクロツキーをつなぐ',
  S.DeviceConnected: '接続',
  S.VSSettings: '1対1設定',
  S.MatchSmartdeviceplayer: 'マッチングスマートデバイスプレイヤー',
  S.Waitingforfriendtoready: 'フレンドの準備を待っています',
  S.Follow: '従う',
  S.Applied: '応用',
  S.Thenumberofslidespersecond: '毎秒のスライド回数はクロツキーのプレイレベルを左右する重要なパラメーターです',
  S.Unknownlocation: '不明な場所',
  S.Solutiondiscussion: '解き方コミュニティ',
  S.Goto: '～へ行く',
  S.FamousGameSlogan: '三国を巡ってランクを上げよう',
  S.FreeGameSlogan: '練習練習、また練習',
  S.LevelGameSlogan: '千ステージを突破して星獲得',
  S.LevelNumGameSlogan: 'ステージクリアで星獲得',
  S.RankGameSlogan: '友だちを誘って一緒にプレイ',
  S.Checkthetutorialguideassistance: 'チュートリアルガイドを参照してヘルプを求めてください',
  S.ThesolutionapproachforDifficultyN: '"難易度%s"の解法のアプローチが解除されました。確認に移動しますか？'
};
