import 'intl_keys.dart';

const fr_FR_res = {
  S.OK: 'D’ACCORD',
  S.Next: 'Prochain',
  S.Cancel: 'Annuler',
  S.Connect: 'Relier',
  S.Dis: 'Déconnecter',
  S.Disconnect: 'Déconnecter',
  S.Devicenotconnected: 'Appareil non connecté',
  S.Klotski: 'Klotski',
  S.NumberPuzzle: 'Puzzle numérique',
  S.Classic: 'Classique',
  S.Practice: 'Pratique',
  S.Stages: 'Étapes',
  S.VS: '1 CONTRE 1',
  S.Devices: 'Dispositifs',
  S.Search: 'Rechercher',
  S.Searching: 'Recherche',
  S.Searchagain: 'Rechercher à nouveau',
  S.Battery: 'Pile',
  S.Switch: 'Interrupteur',
  S.FirmwareVersion: 'Firmware Version',
  S.Bluetoothnotenabled: 'Bluetooth non activé',
  S.Enablebluetooth: 'Activer le bluetooth',
  S.Renamedevice: 'Renommer l’appareil',
  S.Disconnectdevice: 'Déconnecter l’appareil',
  S.FirmwareUpgrade: 'Micrologiciel',
  S.Upgradefirmwareto: 'Mise à niveau du micrologiciel vers',
  S.FirmwareupgradingPleasedonotclosetheapp: 'Mise à niveau du firmwarel, Veuillez ne pas fermer l’application',
  S.Customize: 'Personnaliser',
  S.SlideTime: 'Diapositive & Temps',
  S.AITutorial: 'Tutoriel IA',
  S.StageSync: 'Synchronisation de scène',
  S.syncappdevicestageprogress:
      'La progression de l’étape de votre appareil intelligent n’est pas la même que celle de l’application. Voulez-vous les synchroniser ?',
  S.Sync: 'Synchronisation',
  S.Records: 'Archives',
  S.Invite: 'Inviter',
  S.Move: 'Se déplace',
  S.PreviousStep: 'Étape précédente',
  S.Speed: ' x',
  S.Puttingoneselfinsomeoneelsesshoes: "Se mettre à la place de quelqu'un d'autre",
  S.ThreeHeroesSwearBrotherhoodInThePeachGarden: 'Les Trois Héros Jurent Fraternité Dans Le Jardin de la Pêche',
  S.FuXisEightTrigramsWaterKanTrigram: "Les Huit Trigrammes de Fu Xi : Trigramme de l'Eau Kan",
  S.PassFiveLevels: 'Passer cinq niveaux',
  S.Domineeringandtyrannical: 'Dominant et tyrannique',
  S.TheThreeBrothersFightAgainstLuBu: 'Les Trois Frères se battent contre Lu Bu',
  S.Drawingaswordandmountingahorse: 'Tirer une épée et monter à cheval',
  S.LiuBeiPaysThreeVisitsToZhugeLiangscottage: 'Liu Bei rend trois visites à la cabane de Zhuge Liang',
  S.Settingfiretotheconnectedcamps: 'Mettre le feu aux camps connectés',
  S.Devicenamemodifiedsuccessfully: 'Terminé',
  S.Failed: 'Raté',
  S.FirmwareUpdateSuccessfully: 'Mise à jour réussie du micrologiciel',
  S.Back: 'Précédent',
  S.Newrecord: 'Nouveau record',
  S.Noscore: 'Pas de score',
  S.PleaseselecttheStageyouwanttosync: 'Veuillez sélectionner la scène que vous souhaitez synchroniser',
  S.GANKlotski: 'GAN Klotski',
  S.Inprogress: 'En cours',
  S.SyncCompleted: 'Terminé',
  S.automatching: 'Correspondance automatique',
  S.Recommendedstage: 'Étape recommandée',
  S.selectachessgame: 'Sélectionnez une partie d’échecs',
  S.quit: 'Démissionner',
  S.Completed: 'Terminé',
  S.pressOKafterplacingthepieces: "Appuyez sur 'OK' après avoir placé les pièces",
  S.recordofClassic: 'Record de classique',
  S.Chessgame: 'Jeu d’échecs',
  S.moves: 'Se déplace',
  S.Score: 'Score',
  S.Selectstage: 'Sélectionner une étape',
  S.Advancedstage: 'Stade avancé',
  S.ultimatechallenge: 'Défi ultime',
  S.Challengefailed: 'Raté',
  S.Placementisabnormalpleaserearrange: 'Le placement est anormal, veuillez réorganiser',
  S.Giveupchallenge: 'Démissionner',
  S.shareGame: 'Partager',
  S.Customchessgame: 'Jeu d’échecs personnalisé',
  S.reset: 'Réinitialisation',
  S.Thischessgamehasnosolutionpleaserearrangethepieces:
      'Ce jeu d’échecs n’a pas de solution, veuillez réorganiser les pièces',
  S.Thischessgameiscompletedpleaserearrange: 'Cette partie d’échecs est terminée, veuillez réorganiser',
  S.Practicerecord: 'Dossier de pratique',
  S.infinitestages: 'Étapes infinies',
  S.Win: 'Gagner',
  S.next: 'Prochain',
  S.youcantgetstarswithAItutorialcontinue: 'Vous ne pouvez pas obtenir d’étoiles avec un tutoriel d’IA, continuez?',
  S.remaining: 'Restant',
  S.Tutorialcompleted: 'Tutoriel terminé',
  S.restart: 'Redémarrer',
  S.stagerecords: 'Records d’étape',
  S.Invitation: 'Invitation d’ami(s)',
  S.stageprogress: 'Statut de l’étape',
  S.Inviting: 'Invitant',
  S.hasdeclined: ' a diminué',
  S.Start: 'Commencer',
  S.Waitingforfriendtostart: 'Attendre que l’ami commence',
  S.Gamehasntstartedleavetheroom: 'Le jeu n’a pas commencé, quitter la pièce?',
  S.Matching: 'Correspondant...',
  S.Esimatedtime: 'Temps estimé ',
  S.seconds: ' s',
  S.matchfound: 'Correspondance trouvée',
  S.startingthegame: 'Démarrage du jeu',
  S.hasquitrematch: "L'adversaire s'est quitté, rematch?",
  S.hasquit: "L'adversaire s'est quitté",
  S.Rematch: 'Revanche',
  S.placement: 'Placement',
  S.observation: 'Observation',
  S.Placing: 'Placement',
  S.Observing: 'Observer',
  S.solving: 'Jouer',
  S.waitfortocompletethegame: "Attendez L'adversaire pour terminer le jeu",
  S.time: 'Heure',
  S.solvemoves: 'Se déplace',
  S.Playagain: 'Rejouer',
  S.timeout: 'Timeout',
  S.failurewithoutfinishStillquit:
      'Ce sera considéré comme un échec si vous quittez sans terminer le jeu. Vous arrêtez encore?',
  S.Reconnecting: 'Rebrancher',
  S.vsrecords: 'Historique 1 vs.1',
  S.Winloss: 'Victoire/perte',
  S.stage3x3: '3 x 3 scènes',
  S.stage4x4: '4 x 4 scènes',
  S.minsago: ' m ago',
  S.hrsago: ' hrs ago',
  S.Stage: 'Étape de difficulté',
  S.dengji: 'Étape',
  S.replayplayback: 'Rejouer',
  S.Norecords: 'Pas d’enregistrements',
  S.Nofriends: 'Pas encore d’amis',
  S.Play: 'Aller sur Jouer',
  S.Forbeginners: 'Pour les débutants',
  S.Joindiscussion: 'Unir',
  S.closeTutorial: 'Fermer',
  S.DeviceInformation: 'Données de l’appareil',
  S.DeviceType: 'Type d’appareil',
  S.Model: 'Modèle d’appareil',
  S.update: 'Mise à jour',
  S.infinite: 'infinies',
  S.Lv: 'Étape %s',
  S.stageprogresoverwrittenunlockedlevel:
      'La progression de l’étape de %s sera écrasée après la synchronisation Vous serez déverrouillé au niveau %s',
  S.PlaywithGANKlotski: 'Jouez avec GAN Klotski',
  S.PlaywithoutGANKlotski: 'Jouez sans GAN Klotski',
  S.gamedonotfinish: 'Le jeu ne se termine pas',
  S.Connecting: 'Connectant',
  S.Donotfinished: 'Ne pas terminer',
  S.Offline: 'Hors-ligne',
  S.Countdown: 'Compte à rebours',
  S.Waiting: 'En attente',
  S.Locked: 'Verrouillé',
  S.connectsmartdeviceunlockVS:
      'Veuillez d’abord connecter l’appareil intelligent « Klotski » pour déverrouiller la fonction 1 VS 1.',
  S.chessCompleted: 'Terminé',
  S.knowresultstillquite: "Vous connaîtrez le résultat une fois que l'adversaire aura terminé, toujours tout à fait ?",
  S.Networkissuepleaseretrylater: 'Problème de réseau, veuillez réessayer plus tard',
  S.Failedcompletegameinspecifiedtime: "Echec de récupération du jeu d’échecs dans le temps défini",
  S.interruptinvitation: 'La fermeture de l’interface interrompra l’invitation, continuera-t-elle?',
  S.friendInviting: 'Invitation',
  S.resolving: 'résolution',
  S.placethepiecesfirst: 'Placez les pièces en premier',
  S.Networkissue: 'Problème de réseau',
  S.Refresh: 'Rafraîchir',
  S.Doubleclickchesstoremove: "Double-cliquez sur une pièce d'échecs sur l'échiquier pour la retirer",
  S.Connected: 'Relié',
  S.Devicenotfound: 'Appareil introuvable',
  S.Quitgame: 'Démissionner',
  S.Random: 'Aléatoire',
  S.ShareScore: 'Partager',
  S.StageCompleted: 'Terminé',
  S.Gamedonotfinishstillquite: 'Le jeu ne se termine pas, Vous arrêtez encore?',
  S.WaitUnLocked: 'Verrouillé',
  S.Downloading: 'Téléchargement',
  S.Downloaded: 'Téléchargé',
  S.gamenotoverregeneratenewgame: 'Le jeu n’est pas terminé. Souhaitez-vous créer un nouveau jeu?',
  S.Selectdate: 'Choisissez une date',
  S.Pleaseoperatesmartdevice: 'Veuillez utiliser un appareil intelligent',
  S.Reachedmaximumlevel: 'Niveau maximal atteint',
  S.disconnectotherdevicesfirst: 'Veuillez d’abord déconnecter les autres appareils',
  S.UpdateruleseveryMondayupdatedata:
      'Les données du classement hebdomadaire sont calculées de 08h00 le lundi à 07h59m59s le lundi suivant en temps universel coordonné. Les scores du classement de la semaine précédente sont établis à 08h00 chaque lundi. \n\nLes règles de classement pour le classement sont les suivantes :\n1. Le classement est basé sur le temps de passage, avec des temps plus courts entraînant des classements plus élevés.\n2. Dans les cas où les temps de passage sont les mêmes, le classement se fait en fonction du nombre de pas effectués, avec moins de pas entraînant des classements plus élevés.\n3. Si les temps de passage et le nombre de pas sont tous deux identiques, le classement se fait en fonction de l\'heure de mise en place dans le classement, avec des heures plus tôt entraînant des classements plus élevés.',
  S.UpdateruleseveryMondayupdatedataCHN:
      'Les données de classement hebdomadaire sont calculées de 00h00 le lundi à 23h59 le dimanche, heure de Beijing. Chaque lundi à 00h00, les résultats du classement de la semaine précédente sont calculés. \n\nLes règles de classement sont les suivantes :\n1. Le classement est basé sur le temps de passage, avec des temps plus courts entraînant des classements plus élevés.\n2. Dans les cas où les temps de passage sont les mêmes, le classement se fait en fonction du nombre de pas effectués, avec moins de pas entraînant des classements plus élevés.\n3. Si les temps de passage et le nombre de pas sont tous deux identiques, le classement se fait en fonction de l\'heure de mise en place dans le classement, avec des heures plus tôt entraînant des classements plus élevés.',
  S.CST: 'HNE',
  S.EDT: 'HAE',
  S.Notonlist: 'Pas sur la liste',
  S.Thisweek: 'Cette semaine',
  S.rankinglist: 'Liste de classement',
  S.UnderAITeachingnotgetscore:
      'Sous Enseignement IA, vous ne pourrez pas obtenir un score. Êtes-vous sûr(e) de vouloir continuer ?',
  S.timesisuseduptoday: 'Le nombre limité de fois est épuisé pour aujourd’hui',
  S.Youhavenchanceslefttoday: "Il vous reste %s chances pour aujourd'hui",
  S.ChallengeSettlement: 'Challenge de règlement',
  S.BrandName: 'Nom de marque',
  S.DeviceModel: 'Modèle d’appareil',
  S.BluetoothAddress: 'Adresse Bluetooth',
  S.ProductName: 'Nom du produit',
  S.Username: 'Nom d’utilisateur',
  S.UploadingPleaseWait: 'Téléchargement en cours, veuillez patienter',
  S.StartChallenge: 'Commencer',
  S.Timehasrunout: 'Le temps est écoulé',
  S.Outofmoves: 'Plus de mouvements disponibles',
  S.OnlyNstepsawayfromsolving: 'C\'est dommage, à seulement %s étapes de résoudre la partie d\'échecs',
  S.Congratulationsonsolvingthechessgame:
      'Félicitations d\'avoir résolu la partie d\'échecs. Venez essayer de vous mettre au défi.',
  S.Basicinstructions: 'Instructions de base',
  S.Solutionapproach: 'Approche de résolution',
  S.Rules: 'Règles',
  S.HowtoPlay: 'Méthode d\'opération',
  S.Modes: 'Modes',
  S.Results: 'Résultats',
  S.CommonTerminology: 'Termes courants',
  S.SharingandLearning: 'Partage et apprentissage',
  S.RulesDetail:
      'En déplaçant les pièces, aidez le grand carré à se déplacer de sa position initiale vers le centre inférieur du plateau de jeu. Les pièces ne peuvent pas être sautées pendant le déplacement. La réussite de la "fuite" constitue une réussite de la mission.',
  S.HowtoPlayDetail:
      'Maintenez la case que vous souhaitez déplacer et faites-la glisser dans n\'importe quelle direction. Le chronomètre commence à fonctionner lorsque vous commencez à faire glisser. Pour les joueurs équipés, connectez d\'abord l\'appareil, placez le plateau de jeu conformément aux instructions de l\'appareil, puis appuyez sur le bouton de confirmation pour lancer le chronomètre.',
  S.ModesDetail:
      'Classique : Ce mode mettra à jour de nouveaux niveaux de temps en temps, publiera 9 niveaux à chaque mise à jour, les anciens niveaux seront remplacés par les nouveaux. Les joueurs peuvent consulter les classements des anciens niveaux en modifiant la période affichée.\n\nÉtapes : Les joueurs peuvent suivre l\'ordre des niveaux pour progresser tout au long du jeu. Ils peuvent obtenir 1 à 3 étoiles selon le temps qu\'ils mettent pour terminer chaque niveau.\n\nPratique : Les joueurs peuvent choisir des niveaux de difficulté de 1 à 13. Le système générera automatiquement des configurations correspondantes. Si un joueur rencontre des difficultés pendant la pratique, ils peuvent cliquer sur l\'enseignement intelligent et suivre l\'IA pour apprendre.\n\n1 CONTRE 1 : Les joueurs peuvent choisir des niveaux de difficulté de 1 à 13 et choisir de se faire automatiquement assortir ou inviter des amis à jouer ensemble. Si l\'auto-assortiment est sélectionné, le système choisira automatiquement d\'autres joueurs du même niveau de difficulté. Si l\'invitation d\'amis est sélectionnée, ils peuvent inviter des amis du site à jouer ensemble, sans aucune restriction de connexion d\'appareil.',
  S.ResultsDetail:
      'Temps : Le temps nécessaire pour terminer le jeu.\nNombre de pas : Chaque déplacement d\'une pièce est compté comme un pas.',
  S.CommonTerminologyDetail:
      'tps : Le nombre de pas effectués par seconde, c\'est-à-dire le nombre de pas divisé par le temps en secondes. Par exemple, tps1.20 signifie que 1,2 pas sont effectués par seconde.\n\nsubX : Les résultats en dessous de X, généralement pour les résultats individuels de temps (en secondes) ou de nombre de pas (en pas). Par exemple, sub3 signifie que le résultat est inférieur à 3 secondes.',
  S.SharingandLearningDetail:
      'Si vous ne pouvez pas passer un niveau, publiez une demande d\'aide sur le groupe de discussion "Beginners Group".',
  S.SharingandLearningDetail2:
      'Si vous souhaitez en savoir plus sur la science de la configuration et des règles de Klotski, rendez-vous sur le groupe de discussion "Science Group".',
  S.SharingandLearningDetail3:
      'Si vous souhaitez en savoir plus sur la résolution de configurations classiques de Klotski, rendez-vous sur le groupe de discussion "Classic Group".',
  S.RulesDetailNum: 'Déplacez les blocs pour les ranger dans l\'ordre croissant de gauche à droite et de haut en bas.',
  S.HowtoPlayDetailNum:
      'Maintenez le bloc que vous souhaitez déplacer et glissez-le dans n\'importe quelle direction pour démarrer le chronomètre. Les joueurs équipés doivent d\'abord se connecter à leur appareil, placer le jeu selon les instructions de l\'appareil, puis appuyer sur le bouton de confirmation pour démarrer le chronomètre.',
  S.ModesDetailNum:
      '3 x 3 scènes : Les blocs numériques sont limités à une zone de 3 x 3. Rangez les blocs numériques de 1 à 8 dans l\'ordre croissant de gauche à droite et de haut en bas. Selon le temps de passage, vous pouvez obtenir de 1 à 3 étoiles.\n\n4 x 4 scènes : Les blocs numériques sont limités à une zone de 4 x 4. Rangez les blocs numériques de 1 à 15 dans l\'ordre croissant de gauche à droite et de haut en bas. Selon le temps de passage, vous pouvez obtenir de 1 à 3 étoiles.\n\nPratique : Les joueurs peuvent choisir la difficulté de 3 x 3 ou 4 x 4. Le système génère automatiquement une configuration correspondant à la difficulté choisie. Si vous rencontrez des difficultés pendant l\'entraînement, vous pouvez cliquer sur "enseignement intelligent" pour suivre l\'AI et apprendre.\n\n1 CONTRE 1 : Les joueurs peuvent choisir la difficulté de 3 x 3 ou 4 x 4 et choisir automatiquement un adversaire ou inviter des amis à jouer. Si vous choisissez une correspondance automatique, le système sélectionnera automatiquement un joueur de difficulté équivalente pour jouer avec vous en fonction de votre équipement. Si vous invitez des amis, vous pouvez jouer ensemble sans restriction de connexion d\'appareil.',
  S.ResultsDetailNum:
      'Temps : temps nécessaire pour terminer le jeu\nNombre de pas : chaque mouvement d\'un bloc compte comme un pas',
  S.CommonTerminologyDetailNum:
      '8p/15p/24p... : représentent les puzzles numériques de troisième/quatrième/cinquième niveaux...\n\ntps : Le nombre de pas par seconde, c\'est-à-dire le nombre de pas divisé par le temps en secondes. Par exemple, tps1.20 signifie que vous pouvez faire 1,2 pas par seconde.\n\nsubX : performance inférieure à X, généralement utilisée pour décrire la performance de temps unique (en secondes) ou le nombre de pas unique. Par exemple, sub3 peut signifier une performance en moins de 3 secondes.',
  S.SharingandLearningDetailNum:
      'Si vous ne pouvez pas passer un niveau, vous pouvez publier une demande d\'aide dans le "Number Puzzle Group".',
  S.HrdTeachTitle: 'Guide du débutant pour Klotski',
  S.NumTeachTitle: 'Guide du débutant pour le Puzzle Numérique',
  S.ContactUs: 'Contactez-nous',
  S.ContactUsDetail:
      'Si vous rencontrez des problèmes lors de l\'utilisation de l\'application, vous pouvez publier vos commentaires dans le groupe ou scanner le code QR pour ajouter "方块仔" pour les commentaires',
  S.LookTeach: 'Voir les instructions',
  S.Time: 'Temps',
  S.Numberofvictories: 'Nombre de victoires de la semaine',
  S.Winrate: 'Taux de victoire',
  S.Smartdeviceplayer: "Joueur d'appareil intelligent",
  S.Ready: 'Schon bereit',
  S.Prepare: 'Préparer',
  S.Thedevicehasbeendisconnected: "Votre dispositif s'est déconnecté",
  S.ProceedtoConnect: 'Procéder à la connexion',
  S.Settings: 'Paramètres',
  S.ConnectKlotski: 'Connecter Klotski',
  S.DeviceConnected: 'Relié',
  S.VSSettings: '1 CONTRE 1 Paramètres',
  S.MatchSmartdeviceplayer: "Correspondant Joueur d'appareil intelligent",
  S.Waitingforfriendtoready: 'Attendre que l’ami Prêt',
  S.Follow: 'Suivre',
  S.Applied: 'Appliqué',
  S.Thenumberofslidespersecond:
      "Les diapositives par seconde sont essentielles pour évaluer la vitesse d'exécution à Klotski",
  S.Unknownlocation: 'Emplacement inconnu',
  S.Solutiondiscussion: 'Discussion sur la résolution',
  S.Goto: 'Aller',
  S.FamousGameSlogan: 'Explorer les Trois Royaumes, grimper au classement',
  S.FreeGameSlogan: 'Exercices réguliers, vitesse exceptionnelle',
  S.LevelGameSlogan: 'Milliers des niveaux pour milliers des étoiles',
  S.LevelNumGameSlogan: 'Passer des niveaux pour collecter des étoiles',
  S.RankGameSlogan: 'Jouer avec vos amis',
  S.Checkthetutorialguideassistance: 'Consultez le guide de tutoriel pour obtenir de l\'aide',
  S.ThesolutionapproachforDifficultyN:
      'L\'approche de solution pour "Difficulté %s" a été débloquée. Souhaitez-vous y jeter un coup d\'œil ?'
};
